'use strict';

const { randomUUID } = require('node:crypto');
const { principal } = require('../src/domain-router-policy');
const { normalizeEvidenceInput } = require('../src/workbench-evidence');
const policy = require('../src/file-channel-policy');
const { extractOriginal } = require('../src/file-channel-extract');

function fileAction(summary, handler) {
  return {
    visibility: 'protected',
    openapi: require('../src/file-channel-openapi').fileOpenApi(null, summary),
    handler,
  };
}
module.exports = {
  name: 'files',
  actions: {
    upload: fileAction('Store an original file in the authenticated tenant', async function (ctx) {
      const { p } = await this.identity(ctx);
      return this.storeFile(ctx, p, ctx.params);
    }),
    read: fileAction(
      'Resolve an original file for document and table processing',
      async function (ctx) {
        const p = principal(ctx);
        const file = await this.readFile(ctx, p, ctx.params.fileId);
        const document = await extractOriginal(file);
        return { ...document, reference: policy.reference(file) };
      }
    ),
    download: fileAction(
      'Download a signed tenant-bound file; audit each retrieval',
      async function (ctx) {
        const { p } = await this.identity(ctx);
        const id = policy.fileId(ctx.params.fileId);
        try {
          const file = await this.readFile(ctx, p, id);
          policy.verifyDownload(ctx.params.ticket, p, file);
          // Fail closed if the audit cannot be persisted before delivering bytes.
          await this.audit(ctx, p, id, 'download', 'allowed');
          return { name: file.name, mimeType: file.mimeType, contentBase64: file.contentBase64 };
        } catch (error) {
          await this.audit(ctx, p, id, 'download', 'denied');
          throw error;
        }
      }
    ),
    remove: fileAction(
      'Physically remove an authorized file and revoke its links',
      async function (ctx) {
        const { p } = await this.identity(ctx);
        return this.removeFile(ctx, p, ctx.params.fileId, 'delete');
      }
    ),
    link: fileAction('Create a seven-day signed link for an authorized file', async function (ctx) {
      const { p } = await this.identity(ctx);
      return this.downloadLink(await this.readFile(ctx, p, ctx.params.fileId));
    }),
    publish: fileAction(
      'Publish generated bytes as a case document and chat download link',
      async function (ctx) {
        const p = principal(ctx);
        if (!ctx.params.caseId) policy.fileError('Fallbezug für erzeugte Dateien erforderlich.');
        const router = this.broker.getLocalService('domain-router');
        await router.loadCase(p, ctx.params.caseId);
        const ref = await this.storeFile(ctx, p, ctx.params);
        const file = await this.readFile(ctx, p, ref.fileId);
        await this.attach(ctx, p, file, ctx.params.caseId);
        const link = this.downloadLink(file);
        return {
          ...ref,
          ...link,
          responseText: `[${file.name.replace(/[\[\]]/g, '')}](${link.url}) (Download sieben Tage gültig; als Fallunterlage abgelegt.)`,
        };
      }
    ),
    attach: fileAction(
      'Attach tenant file references to existing case evidence',
      async function (ctx) {
        const p = principal(ctx);
        await this.broker.getLocalService('domain-router').loadCase(p, ctx.params.caseId);
        for (const id of ctx.params.fileIds || [])
          await this.attach(ctx, p, await this.readFile(ctx, p, id), ctx.params.caseId);
        return { attached: true };
      }
    ),
    purge: fileAction(
      'Apply configured retention and revoke expired file content',
      async function (ctx) {
        const p = principal(ctx);
        const { docs } = await this.object(ctx, 'query', p.tenantId, null, {
          limit: 1000,
          selector: { 'payload.expiresAt': { $lte: Date.now() } },
        });
        let removed = 0;
        for (const doc of docs)
          if (doc.payload.expiresAt <= Date.now()) {
            await this.removeFile(ctx, p, doc.key, 'retention');
            removed++;
          }
        return { removed };
      }
    ),
  },
  methods: {
    async removeFile(ctx, p, id, operation) {
      const { payload: file } = await this.object(ctx, 'get', p.tenantId, policy.fileId(id));
      policy.authorizeFile(p, { ...file, expiresAt: Number.MAX_SAFE_INTEGER });
      await this.audit(ctx, p, file.fileId, operation, 'allowed');
      await this.object(ctx, 'delete', p.tenantId, file.fileId);
      const wb = this.broker.getLocalService('workbench');
      const rows = await wb.evidenceDb.allDocs({ include_docs: true });
      for (const { doc } of rows.rows)
        if (
          doc.tenantId === p.tenantId &&
          (doc.sourceRef?.fileId === file.fileId ||
            doc.extracts?.document?.sourceId === file.fileId)
        )
          await wb.evidenceDb.remove(doc);
      await wb.evidenceDb.compact();
      await this.broker.getLocalService('object-store').db.compact();
      return { deleted: true, fileId: file.fileId };
    },
    async identity(ctx) {
      const wb = this.broker.getLocalService('workbench');
      const token = ctx.meta.apiToken;
      const headers = ctx.meta.requestHeaders || {};
      const envelope = {
        channel: 'open-webui',
        openWebuiOrgId: ctx.params.openWebuiOrgId ?? token?.externalOrgId,
        openWebuiUserId: ctx.params.openWebuiUserId ?? headers['x-openwebui-user-id'],
        openWebuiUserEmail: headers['x-openwebui-user-email'],
      };
      // Reuse #736's org check, tenant mapping, roles, clearance and delegation audit.
      return wb.resolveTurnPrincipal(ctx, envelope);
    },
    object(ctx, operation, tenantId, key, extra = {}) {
      return ctx.call(
        `object-store.${operation}`,
        { namespace: policy.namespace(tenantId), ...(key ? { key } : {}), ...extra },
        { meta: { ...ctx.meta, fileStoreCapability: policy.storeCapability } }
      );
    },
    async readFile(ctx, p, id) {
      const { payload } = await this.object(ctx, 'get', p.tenantId, policy.fileId(id));
      policy.authorizeFile(p, payload);
      return payload;
    },
    async storeFile(ctx, p, input) {
      const validated = policy.validateFile(input);
      require('../src/workbench-evidence').assertSensitivityAllowed(
        validated.sensitivityLevel,
        p.clearance
      );
      // Hook must return an explicit clean verdict. Scanner errors never expose content.
      const scanner = this.settings.scanAction || process.env.CET_FILE_SCAN_ACTION;
      if (scanner) {
        let verdict;
        try {
          verdict = await ctx.call(
            scanner,
            { bytes: validated.bytes, mimeType: validated.mimeType, hash: validated.hash },
            { timeout: policy.fileSetting('SCAN_TIMEOUT_MS', 30000) }
          );
        } catch (_error) {
          policy.fileError(
            'Virenscan nicht verfügbar. Datei nicht gespeichert.',
            503,
            'FILE_SCAN_UNAVAILABLE'
          );
        }
        if (verdict?.clean !== true)
          policy.fileError('Virenscan hat die Datei abgewiesen.', 422, 'FILE_SCAN_REJECTED');
      }
      const requiredClearance = input.requiredClearance || [];
      if (
        !Array.isArray(requiredClearance) ||
        requiredClearance.some((level) => !['restricted', 'highly_sensitive'].includes(level))
      )
        policy.fileError('Ungültige Vertraulichkeitsfreigabe.');
      for (const level of requiredClearance)
        require('../src/workbench-evidence').assertSensitivityAllowed(level, p.clearance);
      const id = validated.hash;
      try {
        const prior = await this.readFile(ctx, p, id);
        // Changing a boundary requires an explicit new version, never hash-based downgrading.
        if (
          prior.sensitivityLevel !== validated.sensitivityLevel ||
          JSON.stringify(prior.requiredClearance || []) !== JSON.stringify(requiredClearance)
        )
          policy.fileError(
            'Identischer Inhalt hat bereits eine andere Vertraulichkeitsstufe.',
            409
          );
        return { ...policy.reference(prior), duplicate: true };
      } catch (error) {
        if (error.type !== 'OBJECT_NOT_FOUND') throw error;
      }
      const file = {
        ...validated,
        requiredClearance,
        bytes: undefined,
        fileId: id,
        tenantId: p.tenantId,
        actorId: p.actorId,
        contentBase64: validated.bytes.toString('base64'),
        version: randomUUID(),
        createdAt: Date.now(),
        expiresAt: Date.now() + policy.fileSetting('RETENTION_DAYS', 30) * 86400000,
      };
      // Serialize per-tenant uploads; ordinary Object Store CAS semantics are unchanged.
      await this.object(ctx, 'put', p.tenantId, id, { payload: file });
      await this.audit(ctx, p, id, 'upload', 'allowed');
      return { ...policy.reference(file), duplicate: false };
    },
    async attach(ctx, p, file, caseId) {
      const wb = this.broker.getLocalService('workbench');
      const evidence = normalizeEvidenceInput(
        {
          evidenceType: 'generic_document',
          sourceType: 'openwebui_file_ref',
          label: file.name,
          sensitivityLevel: file.sensitivityLevel,
          fileHash: `sha256:${file.hash}`,
          sourceRef: {
            fileId: file.fileId,
            fileName: file.name,
            mimeType: file.mimeType,
            size: file.size,
            fileHash: `sha256:${file.hash}`,
          },
        },
        { ...p, caseId }
      );
      return wb.store.saveEvidence({
        ...evidence,
        tenantId: p.tenantId,
        actorId: p.actorId,
        caseId,
      });
    },
    downloadLink(file) {
      const { ticket, expiresAt } = policy.signDownload(file);
      const base = process.env.CET_FILE_PUBLIC_BASE_URL || '';
      return { url: `${base}/v1/files/${file.fileId}/content?ticket=${ticket}`, expiresAt };
    },
    audit(ctx, p, id, operation, outcome) {
      return ctx.call(
        'object-store.put',
        {
          namespace: policy.namespace(p.tenantId).replace(/^files:/, 'files_audit:'),
          key: randomUUID(),
          payload: {
            tenantId: p.tenantId,
            actorId: p.actorId,
            fileId: id,
            operation,
            outcome,
            at: new Date().toISOString(),
          },
        },
        { meta: { ...ctx.meta, fileStoreCapability: policy.storeCapability } }
      );
    },
  },
  settings: { scanAction: null },
  hooks: {
    before: {
      upload: async function serializeUpload(ctx) {
        // The lock itself is acquired in the action wrapper below through the service queue.
        if (!this.uploadQueues) this.uploadQueues = new Map();
        const tenant = ctx.meta.apiToken?.tenantId || ctx.meta.tenantId;
        const previous = this.uploadQueues.get(tenant) || Promise.resolve();
        let release;
        const next = new Promise((resolve) => {
          release = resolve;
        });
        this.uploadQueues.set(tenant, next);
        ctx.meta.fileUploadRelease = () => {
          release();
          if (this.uploadQueues.get(tenant) === next) this.uploadQueues.delete(tenant);
        };
        await previous;
      },
    },
    after: {
      upload: function releaseUpload(ctx, result) {
        ctx.meta.fileUploadRelease?.();
        return result;
      },
    },
    error: {
      upload: function releaseFailedUpload(ctx, error) {
        ctx.meta.fileUploadRelease?.();
        throw error;
      },
    },
  },
};

for (const kind of ['upload', 'download', 'remove', 'link']) {
  const action = module.exports.actions[kind];
  action.openapi = require('../src/file-channel-openapi').fileOpenApi(kind, action.openapi.summary);
}
