/**
 * Capability Broker v1 curated catalog.
 *
 * Domain capability -> preferred action path -> action metadata hints.
 * Auto-discovery may add supplemental candidates, but this curated list remains
 * the primary decision layer in v1.
 */

const BROKER_SCHEMA_VERSION = 'cernion.capabilityRecommendation.v1';

const INTERFACE_PLACEHOLDER_CAPABILITY = {
  capability: 'interface_placeholder',
  domain: 'governance',
  abstractionLevel: 'explicit_gap_marker',
  intent: 'mark_unknown_execution_gap',
  keywords: [],
  preferredActions: [
    'interface-placeholder.markGap',
    'interface-placeholder.requestEvidence',
    'interface-placeholder.listGaps',
  ],
  fallbackActions: ['interface-placeholder.markGap'],
  avoid: ['query.ask', 'query.askLearned'],
  requiredInputs: [
    {
      name: 'role',
      label: 'Betroffene Rolle / Capability Owner',
      type: 'string',
      required: true,
    },
    {
      name: 'reason',
      label: 'Gap Reason',
      type: 'string',
      required: true,
    },
  ],
  risksAndNotes: [
    'Placeholder sind explizite Lückenmarker und keine fachliche Wahrheit.',
    'confidence bleibt immer low bis zur Auflösung mit Evidenz oder Entscheidung.',
  ],
  routingPattern: 'explicit_gap_marker',
  isFallback: true,
};

const CURATED_CAPABILITIES = [
  {
    capability: 'cya_assessment_briefing',
    domain: 'cya',
    abstractionLevel: 'journalistic_risk_briefing',
    intent: 'cya.generate',
    secondaryIntents: ['interface_placeholder', 'mark_unknown_execution_gap'],
    keywords: [
      'versorgungssicherheit',
      'belastbare aussagen',
      'unsicherheiten',
      'journalistisch',
      'journalistisches fazit',
      'quellen-hinweis',
      'kernaussagen',
      'fazit',
    ],
    preferredActions: [
      'interface-placeholder.markGap',
      'interface-placeholder.requestEvidence',
      'interface-placeholder.listGaps',
    ],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'role',
        label: 'Analystenrolle',
        type: 'string',
        required: false,
        default: 'cya_analyst',
      },
    ],
    risksAndNotes: [
      'CYA-Antworten müssen Unsicherheit und Evidenzstatus transparent markieren.',
      'Ohne belastbare Evidenz bleibt die Antwort als risikobewusste Einordnung gekennzeichnet.',
    ],
    routingPattern: 'cya_journalistic_briefing',
  },
  {
    capability: 'blindflug_radar_anomaly_detection',
    domain: 'znp_blindflug_radar',
    abstractionLevel: 'domain_workflow',
    intent: 'detect_disturbance_anomalies_and_correlate',
    keywords: [
      'blindflug',
      'radar',
      'disturbance',
      'störung',
      'störungen',
      'investitionssignal',
      'bottleneck',
      'redispatch',
    ],
    preferredActions: ['v1.blindflug-radar.scan', 'znp.correlateDisturbance'],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['query.ask'],
    requiredInputs: [
      {
        name: 'vnbId',
        label: 'VNB Identifier',
        type: 'string',
        required: true,
      },
      {
        name: 'projectId',
        label: 'ZNP Project ID',
        type: 'string',
        required: true,
      },
    ],
    risksAndNotes: [
      'Anomalies must be routed through interface-placeholder if evidence is missing.',
      'High severity anomalies require HITL creation via ZNP correlation.',
    ],
    routingPattern: 'blindflug_znp_correlation',
  },
  {
    capability: 'znp_portfolio_assessment',
    domain: 'zielnetzplanung',
    abstractionLevel: 'layered_portfolio_logic',
    intent: 'assess_znp_portfolio',
    keywords: [
      'portfolio',
      'zielnetzplanung',
      'znp',
      'fnav',
      'kaufmännische',
      'kaufmaennische',
      'layer 0',
      'layer 2',
      'strategic assumption',
      'strategische annahme',
    ],
    preferredActions: ['znp.assessPortfolio'],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'projectId',
        label: 'ZNP Project ID',
        type: 'string',
        required: true,
      },
      {
        name: 'kaufmaennischeFreigabeFnav',
        label: 'Kaufmännische fNAV-Freigabe',
        type: 'boolean',
        required: false,
        default: false,
      },
    ],
    risksAndNotes: [
      'Resultate müssen provenanceFlags transparent ausweisen (Layer 0/2/2.5).',
      'Fehlende kaufmännische fNAV-Freigabe bleibt manueller Hard-Blocker.',
      'Strategische Annahmen sind bewusst niedriger reliabel als gemessene Layer-2-Daten.',
    ],
    routingPattern: 'znp_hybrid_portfolio_assessment',
  },
  {
    capability: 'netzfahrplan_fnav_assessment',
    domain: 'grid_connection_flexibility',
    abstractionLevel: 'deterministic_phase5_workflow',
    intent: 'grid-connection.fnav',
    secondaryIntents: ['assess_fnav_as_kupferalternative'],
    keywords: [
      'netzfahrplan',
      'fnav',
      'flexibler netzanschlussvertrag',
      'kupferausbau',
      'n-1',
      'headroom',
      'firm capacity',
      'flexible capacity',
      '§14a',
    ],
    preferredActions: [
      'grid-connection.fnavValidate',
      'grid-operations.netzfahrplanGenerate',
      'finance-agent.fnavEconomics',
    ],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'requestedCapacityKW',
        label: 'Requested Capacity (kW)',
        type: 'number',
        required: true,
      },
      {
        name: 'voltageLevel',
        label: 'Voltage Level',
        type: 'string',
        required: false,
        default: 'MS',
      },
    ],
    risksAndNotes: [
      'Governance blockers may create interface placeholders and HITL references when legal or contractual certainty is missing.',
      'N-1 defaults come from domain-config unless explicit tenant/project/scenario overrides are supplied.',
      'Commercial evaluation is additive; technical feasibility remains deterministic and independent.',
    ],
    routingPattern: 'phase5_netzfahrplan_fnav_assessment',
  },
  {
    capability: 'residual_load_forecast_for_dso',
    domain: 'grid-operations',
    abstractionLevel: 'domain_workflow',
    intent: 'residual_load_forecast_for_dso',
    keywords: [
      'residuallast',
      'residual load',
      'co2',
      'co₂',
      'lastverschieb',
      'beschaffungsplanung',
      'flexibilitätsfenster',
      'stadtwerk',
      'vnb',
      'dso',
    ],
    preferredActions: [
      'grid-operations.marketPartners',
      'grid-operations.vnbLookup',
      'residual-load.netResidualLoad',
      'energy-market.co2Intensity',
      'energy-market.prices',
    ],
    fallbackActions: ['grid-operations.marketPartners', 'residual-load.netResidualLoad'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'query',
        label: 'Netzbetreiber / Stadtwerk',
        type: 'string',
        required: true,
      },
      {
        name: 'forecastDays',
        label: 'Forecast-Tage',
        type: 'number',
        required: false,
      },
    ],
    risksAndNotes: [
      'Region für residual-load als Stadtname aus marketPartners-Kontakt ableiten.',
      'Bei fehlender SNB-ID mit BDEW-Code + VNB-Name weiterarbeiten.',
    ],
    routingPattern: 'vnb_resolution_plus_residual_load_co2_prices',
  },
  {
    capability: 'vdmi_role_boundary_governance',
    domain: 'vdmi-governance',
    abstractionLevel: 'governance_role_boundary',
    intent: 'vdmi_role_boundary_governance',
    keywords: [
      'rollen',
      'rolle',
      'rollengrenze',
      'schnittstellen',
      'zulässige aussagen',
      'projektträger nicht netzbetreiber',
      'ohne formales netzanschlussbegehren',
      'netzanschlussbegehren',
      '§17 enwg',
      '17 enwg',
      'arealnetzbetreiber',
      'darf keine netzanschlusszusage treffen',
      'netzanschlusszusage',
      'bedarfs',
      'antragsteller',
      'gatekeeper',
    ],
    preferredActions: ['vdmi.agentRole', 'vdmi.context'],
    fallbackActions: ['vdmi.agentRole', 'interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'agentId',
        label: 'Akteur-ID für Rollenprüfung',
        type: 'string',
        required: false,
      },
      {
        name: 'processType',
        label: 'Prozesstyp (z.B. grid-connection-governance)',
        type: 'string',
        required: false,
      },
    ],
    risksAndNotes: [
      'Ohne formales Netzanschlussbegehren keine verbindliche Kapazitäts- oder Übergabepunkt-Zusage.',
      'Projektträger/Business Owner ist nicht automatisch Netzbetreiber-Gatekeeper.',
      'Mehrrollen je Akteur task-spezifisch auswerten (nicht first-match).',
    ],
    routingPattern: 'vdmi_role_boundary_governance',
  },
  {
    capability: 'vdmi_asset_validation_governance',
    domain: 'vdmi-governance',
    abstractionLevel: 'governance_asset_validation',
    intent: 'vdmi_asset_validation_governance',
    keywords: [
      'asset validation',
      'asset-validierung',
      'asset validierung',
      'asset-prüfung',
      'asset pruefung',
      'assetklasse',
      'evidence',
      'evidenz',
      'nachweis',
      'beleg',
      'forbidden assumption',
      'verbotene annahme',
      'risk factors',
      'risikofaktoren',
      'grid-connection-asset-validation',
    ],
    preferredActions: ['vdmi.dossier', 'vdmi.negotiationTrace', 'vdmi.agentRole'],
    fallbackActions: ['vdmi.dossier', 'interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'taskId',
        label: 'Task-ID für Asset-Prüfung',
        type: 'string',
        required: true,
      },
      {
        name: 'processType',
        label: 'Prozesstyp (z.B. grid-connection-asset-validation)',
        type: 'string',
        required: false,
      },
    ],
    risksAndNotes: [
      'Asset-Validierung muss Evidenzlücken explizit ausweisen und darf keine fehlenden Nachweise erfinden.',
      'Risikofaktoren und verbotene Annahmen sind task-spezifisch aus der Matrix abzuleiten.',
      'Bei unvollständiger Evidenz nur zulässige Optionen mit Next Actions für V-Entscheidung ausgeben.',
    ],
    routingPattern: 'vdmi_asset_validation_governance',
  },
  {
    capability: 'vdmi_grid_connection_decision_governance',
    domain: 'vdmi-governance',
    abstractionLevel: 'governance_grid_connection_decision',
    intent: 'vdmi_grid_connection_decision_governance',
    keywords: [
      'anschlusszusage',
      'kapazitätszusage',
      'kapazitaetszusage',
      'übergabepunkt',
      'uebergabepunkt',
      'netzbetreiberentscheidung',
      'formales netzanschlussbegehren',
      '§17 enwg',
      '17 enwg',
      'belastbare zusage',
      'darf der netzbetreiber zusagen',
      'decision_blocked_pending_formal_request',
    ],
    preferredActions: ['vdmi.dossier', 'vdmi.negotiationTrace', 'vdmi.agentRole'],
    fallbackActions: ['vdmi.dossier', 'interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'taskId',
        label: 'Task-ID (optional, wird aus knownContext oder Matrix abgeleitet)',
        type: 'string',
        required: false,
      },
      {
        name: 'processType',
        label: 'Prozesstyp (z.B. grid-connection-governance)',
        type: 'string',
        required: false,
      },
      {
        name: 'matrixId',
        label: 'VDMI Matrix-ID (optional)',
        type: 'string',
        required: false,
      },
      {
        name: 'processId',
        label: 'VDMI Process-/Job-ID (optional)',
        type: 'string',
        required: false,
      },
    ],
    risksAndNotes: [
      'Ohne formales Netzanschlussbegehren (§17 EnWG) keine belastbare Anschluss-/Kapazitätszusage.',
      'Entscheidungskontext muss Evidenzlücken und verbotene Annahmen explizit enthalten.',
      'Wenn Task/V-Akteur nicht eindeutig auflösbar ist, mit interface-placeholder formal stoppen.',
    ],
    routingPattern: 'vdmi_grid_connection_decision_governance',
  },
  {
    capability: 'grid_operator_identity_resolution',
    domain: 'grid-operations',
    abstractionLevel: 'deterministic_lookup',
    intent: 'resolve_grid_operator_identity',
    keywords: ['netzbetreiber', 'vnb', 'dso', 'stadtwerke', 'bdew', 'snb'],
    preferredActions: ['grid-operations.marketPartners', 'grid-operations.vnbLookup'],
    fallbackActions: ['grid-operations.marketPartners'],
    avoid: [],
    requiredInputs: [
      {
        name: 'query',
        label: 'Netzbetreiber / Stadtwerk',
        type: 'string',
        required: true,
      },
    ],
    risksAndNotes: ['Bei mehrdeutigen Treffern Top-3 Kandidaten vergleichen.'],
    routingPattern: 'vnb_identity_resolution',
  },
  {
    capability: 'inhouse_timeseries_analysis',
    domain: 'inhouse',
    abstractionLevel: 'domain_workflow',
    intent: 'inhouse_timeseries_analysis',
    keywords: ['inhouse', 'csv', 'upload', 'datasource', 'messwerte', 'lastprofil'],
    preferredActions: ['datasource-cache.query', 'in-memory-join.meteringSpotCost'],
    fallbackActions: ['datasource-cache.query'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'sourceId',
        label: 'Inhouse-Datasource',
        type: 'string',
        required: true,
      },
    ],
    risksAndNotes: [
      'Inhouse-Daten niemals über generische SQL-/Query-Tools abfragen.',
      'Aggregation/Join in-memory durchführen.',
    ],
    routingPattern: 'inhouse_datasource_cache_query',
  },
  {
    capability: 'mastr_asset_inventory',
    domain: 'assets',
    abstractionLevel: 'aggregated_service',
    intent: 'mastr_asset_inventory',
    keywords: [
      'mastr',
      'anlage',
      'anlagen',
      'pv',
      'wind',
      'speicher',
      'redispatch',
      'fernsteuerbarkeit',
    ],
    preferredActions: [
      'grid-operations.marketPartners',
      'grid-operations.vnbLookup',
      'assets.solar',
    ],
    fallbackActions: ['assets.all'],
    avoid: ['oep.query'],
    requiredInputs: [
      {
        name: 'query',
        label: 'Betreiber / Region',
        type: 'string',
        required: true,
      },
    ],
    risksAndNotes: [
      'Betriebsstatus und Netzbetreiberprüfstatus getrennt behandeln.',
      'OEP ist für reale Assetlisten sekundär gegenüber MaStR.',
    ],
    routingPattern: 'mastr_primary_asset_lookup',
  },
  {
    capability: 'oep_research_dataset_discovery',
    domain: 'oep',
    abstractionLevel: 'raw_data',
    intent: 'oep_research_dataset_discovery',
    keywords: ['oep', 'open energy platform', 'szenario', 'tyndp', 'nep'],
    preferredActions: ['oep.energyTables', 'oep.search', 'oep.query'],
    fallbackActions: ['oep.listSchemas', 'oep.listTables', 'oep.getTableMeta'],
    avoid: [],
    requiredInputs: [
      {
        name: 'q',
        label: 'Suchbegriff',
        type: 'string',
        required: false,
      },
    ],
    risksAndNotes: ['OEP-Daten als Szenario-/Forschungsquelle behandeln, nicht als Primärquelle für Assets.'],
    routingPattern: 'oep_discovery_chain',
  },
  {
    capability: 'financier_due_diligence_assessment',
    domain: 'finance-agent',
    abstractionLevel: 'regulatory_finance_due_diligence',
    intent: 'financier_due_diligence_assessment',
    keywords: [
      'due diligence',
      'risk assessment',
      'kreditausschuss',
      'credit committee',
      'bankability',
      'condition precedent',
      'financier',
      'finanzierer',
      'vorläufiges risk assessment',
    ],
    preferredActions: ['finance-agent.analyze'],
    fallbackActions: ['finance-agent.analyze', 'interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'query',
        label: 'Due-Diligence-Frage',
        type: 'string',
        required: true,
      },
    ],
    risksAndNotes: [
      'Antworten müssen evidenzgebunden bleiben (keine erfundenen regulatorischen Fakten).',
      'Unsicherheiten/Annahmen explizit als vorläufig markieren (Condition-Precedent-Logik).',
      'Bei fehlender Evidenz sind Nachweise konkret anzufordern statt auf missing-interface zu fallen.',
    ],
    routingPattern: 'financier_due_diligence_assessment',
  },
  {
    capability: 'vnb_kpi_benchmark_comparison',
    domain: 'finance-agent',
    abstractionLevel: 'aggregated_kpi_comparison',
    intent: 'vnb_kpi_benchmark_comparison',
    keywords: [
      'benchmark',
      'vergleich',
      'potenzialvergleich',
      'nachbar',
      'wettbewerber',
      'kpi',
      'anschlussdauer',
      'digitalisierungsindex',
      'umsetzungsquote',
      'ewk',
    ],
    preferredActions: [
      'grid-operations.marketPartners',
      'ewk-monitoring.benchmarkVnb',
      'grid-operations.vnbLookup',
      'assets.all',
    ],
    fallbackActions: ['grid-operations.marketPartners', 'ewk-monitoring.benchmarkVnb'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'vnb1Name',
        label: 'First VNB Name',
        type: 'string',
        required: true,
      },
      {
        name: 'vnb2Name',
        label: 'Second VNB Name',
        type: 'string',
        required: true,
      },
      {
        name: 'comparisonDimensions',
        label: 'Comparison Dimensions',
        type: 'array',
        items: 'string',
        default: ['anschlussdauer', 'digitalisierungsindex', 'umsetzungsquote'],
        required: false,
      },
    ],
    risksAndNotes: [
      'Both VNBs must be resolvable via marketPartners.',
      'EWK data is annual BNetzA source; may not reflect current operational status.',
      'Hard evidence only; no hypothetical synthesis unless explicitly requested.',
    ],
    routingPattern: 'vnb_kpi_benchmark_multi_step',
  },
];

const GLOBAL_DO_NOT_USE = [
  {
    action: 'query.ask',
    reason: 'Nur nutzen, wenn kein deterministischer oder domänenspezifischer Pfad verfügbar ist.',
  },
  {
    action: 'query.askLearned',
    reason: 'Nur nutzen, wenn kein deterministischer oder domänenspezifischer Pfad verfügbar ist.',
  },
];

module.exports = {
  BROKER_SCHEMA_VERSION,
  CURATED_CAPABILITIES,
  INTERFACE_PLACEHOLDER_CAPABILITY,
  GLOBAL_DO_NOT_USE,
};
