/**
 * Capability Broker v1 curated catalog.
 *
 * Domain capability -> preferred action path -> action metadata hints.
 * Auto-discovery may add supplemental candidates, but this curated list remains
 * the primary decision layer in v1.
 */

const BROKER_SCHEMA_VERSION = 'cernion.capabilityRecommendation.v1';

const INTERFACE_PLACEHOLDER_CAPABILITY = {
  capability: 'interface_placeholder',
  domain: 'governance',
  abstractionLevel: 'explicit_gap_marker',
  intent: 'mark_unknown_execution_gap',
  keywords: [],
  preferredActions: [
    'interface-placeholder.markGap',
    'interface-placeholder.requestEvidence',
    'interface-placeholder.listGaps',
  ],
  fallbackActions: ['interface-placeholder.markGap'],
  avoid: ['query.ask', 'query.askLearned'],
  requiredInputs: [
    {
      name: 'role',
      label: 'Betroffene Rolle / Capability Owner',
      type: 'string',
      required: true,
    },
    {
      name: 'reason',
      label: 'Gap Reason',
      type: 'string',
      required: true,
    },
  ],
  risksAndNotes: [
    'Placeholder sind explizite Lückenmarker und keine fachliche Wahrheit.',
    'confidence bleibt immer low bis zur Auflösung mit Evidenz oder Entscheidung.',
  ],
  routingPattern: 'explicit_gap_marker',
  isFallback: true,
};

const CURATED_CAPABILITIES = [
  {
    capability: 'cya_assessment_briefing',
    domain: 'cya',
    abstractionLevel: 'journalistic_risk_briefing',
    intent: 'cya.generate',
    secondaryIntents: ['interface_placeholder', 'mark_unknown_execution_gap'],
    keywords: [
      'versorgungssicherheit',
      'belastbare aussagen',
      'unsicherheiten',
      'journalistisch',
      'journalistisches fazit',
      'quellen-hinweis',
      'kernaussagen',
      'fazit',
    ],
    preferredActions: [
      'interface-placeholder.markGap',
      'interface-placeholder.requestEvidence',
      'interface-placeholder.listGaps',
    ],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'role',
        label: 'Analystenrolle',
        type: 'string',
        required: false,
        default: 'cya_analyst',
      },
    ],
    risksAndNotes: [
      'CYA-Antworten müssen Unsicherheit und Evidenzstatus transparent markieren.',
      'Ohne belastbare Evidenz bleibt die Antwort als risikobewusste Einordnung gekennzeichnet.',
    ],
    routingPattern: 'cya_journalistic_briefing',
  },
  {
    capability: 'blindflug_radar_anomaly_detection',
    domain: 'znp_blindflug_radar',
    abstractionLevel: 'domain_workflow',
    intent: 'detect_disturbance_anomalies_and_correlate',
    keywords: [
      'blindflug',
      'radar',
      'disturbance',
      'störung',
      'störungen',
      'investitionssignal',
      'bottleneck',
      'redispatch',
    ],
    preferredActions: ['v1.blindflug-radar.scan', 'znp.correlateDisturbance'],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['query.ask'],
    requiredInputs: [
      {
        name: 'vnbId',
        label: 'VNB Identifier',
        type: 'string',
        required: true,
      },
      {
        name: 'projectId',
        label: 'ZNP Project ID',
        type: 'string',
        required: true,
      },
    ],
    risksAndNotes: [
      'Anomalies must be routed through interface-placeholder if evidence is missing.',
      'High severity anomalies require HITL creation via ZNP correlation.',
    ],
    routingPattern: 'blindflug_znp_correlation',
  },
  {
    capability: 'znp_portfolio_assessment',
    domain: 'zielnetzplanung',
    abstractionLevel: 'layered_portfolio_logic',
    intent: 'assess_znp_portfolio',
    keywords: [
      'portfolio',
      'zielnetzplanung',
      'znp',
      'fnav',
      'kaufmännische',
      'kaufmaennische',
      'layer 0',
      'layer 2',
      'strategic assumption',
      'strategische annahme',
    ],
    preferredActions: ['znp.assessPortfolio'],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'projectId',
        label: 'ZNP Project ID',
        type: 'string',
        required: true,
      },
      {
        name: 'kaufmaennischeFreigabeFnav',
        label: 'Kaufmännische fNAV-Freigabe',
        type: 'boolean',
        required: false,
        default: false,
      },
    ],
    risksAndNotes: [
      'Resultate müssen provenanceFlags transparent ausweisen (Layer 0/2/2.5).',
      'Fehlende kaufmännische fNAV-Freigabe bleibt manueller Hard-Blocker.',
      'Strategische Annahmen sind bewusst niedriger reliabel als gemessene Layer-2-Daten.',
    ],
    routingPattern: 'znp_hybrid_portfolio_assessment',
  },
  {
    capability: 'netzfahrplan_fnav_assessment',
    domain: 'grid_connection_flexibility',
    abstractionLevel: 'deterministic_phase5_workflow',
    intent: 'grid-connection.fnav',
    secondaryIntents: ['assess_fnav_as_kupferalternative'],
    keywords: [
      'netzfahrplan',
      'fnav',
      'flexibler netzanschlussvertrag',
      'netzsignal',
      'netzsignal vorrang',
      'vertragsgate',
      'grid signal priority',
      'kupferausbau',
      'n-1',
      'headroom',
      'firm capacity',
      'flexible capacity',
      '§14a',
    ],
    preferredActions: [
      'grid-connection.fnavValidate',
      'grid-operations.netzfahrplanGenerate',
      'finance-agent.fnavEconomics',
    ],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'requestedCapacityKW',
        label: 'Requested Capacity (kW)',
        type: 'number',
        required: true,
      },
      {
        name: 'voltageLevel',
        label: 'Voltage Level',
        type: 'string',
        required: false,
        default: 'MS',
      },
    ],
    risksAndNotes: [
      'Governance blockers may create interface placeholders and HITL references when legal or contractual certainty is missing.',
      'N-1 defaults come from domain-config unless explicit tenant/project/scenario overrides are supplied.',
      'Commercial evaluation is additive; technical feasibility remains deterministic and independent.',
    ],
    routingPattern: 'phase5_netzfahrplan_fnav_assessment',
  },
  {
    capability: 'residual_load_forecast_for_dso',
    domain: 'grid-operations',
    abstractionLevel: 'domain_workflow',
    intent: 'residual_load_forecast_for_dso',
    keywords: [
      'residuallast',
      'residual load',
      'co2',
      'co₂',
      'lastverschieb',
      'beschaffungsplanung',
      'flexibilitätsfenster',
      'stadtwerk',
      'vnb',
      'dso',
    ],
    preferredActions: [
      'grid-operations.marketPartners',
      'grid-operations.vnbLookup',
      'residual-load.netResidualLoad',
      'energy-market.co2Intensity',
      'energy-market.prices',
    ],
    fallbackActions: ['grid-operations.marketPartners', 'residual-load.netResidualLoad'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'query',
        label: 'Netzbetreiber / Stadtwerk',
        type: 'string',
        required: true,
      },
      {
        name: 'forecastDays',
        label: 'Forecast-Tage',
        type: 'number',
        required: false,
      },
    ],
    risksAndNotes: [
      'Region für residual-load als Stadtname aus marketPartners-Kontakt ableiten.',
      'Bei fehlender SNB-ID mit BDEW-Code + VNB-Name weiterarbeiten.',
    ],
    routingPattern: 'vnb_resolution_plus_residual_load_co2_prices',
  },
  {
    capability: 'cross_commodity_supply_security_lagebild',
    domain: 'market-operations',
    abstractionLevel: 'read_only_evidence_briefing',
    intent: 'cross_commodity_supply_security_lagebild',
    keywords: [
      'gasspeicher',
      'agsi',
      'gie',
      'entso-e',
      'entsoe',
      'versorgungssicherheit',
      'lagebild',
      'lage-/beschaffungsrunde',
      'beschaffungsrunde',
      'voralarm',
      'beobachtungsmodus',
      'fernwaerme',
      'fernwärme',
      'kwk',
      'waermelast',
      'wärmelast',
      'windprognose',
      'lastprognose',
      'day-ahead',
    ],
    preferredActions: [
      'gas-storage.countryStorage',
      'gas-storage.supplySecurityCheck',
      'entsoe.loadForecast',
      'entsoe.windSolarForecast',
      'entsoe.dayAheadPrices',
    ],
    fallbackActions: ['gas-storage.countryStorage', 'entsoe.loadForecast'],
    avoid: ['query.ask', 'query.askLearned', 'interface-placeholder.markGap'],
    requiredInputs: [
      {
        name: 'region',
        label: 'ENTSO-E Region / Bidding Zone',
        type: 'string',
        required: false,
        default: 'Germany',
      },
      {
        name: 'country',
        label: 'AGSI Country Code',
        type: 'string',
        required: false,
        default: 'DE',
      },
      {
        name: 'dateFrom',
        label: 'Startdatum',
        type: 'string',
        required: false,
      },
      {
        name: 'dateTo',
        label: 'Enddatum',
        type: 'string',
        required: false,
      },
    ],
    risksAndNotes: [
      'Nur read-only Marktdaten und Systemdaten; keine Handelsentscheidung, keine Notfallstufe und keine operative Anweisung ableiten.',
      'AGSI/GIE und ENTSO-E sind externe Indikatoren und muessen von internen Portfolio- und Leitwartenmeldungen getrennt bleiben.',
      'Bei fehlenden Schwellenwerten hoechstens Beobachtungsmodus oder Datenanforderung empfehlen.',
    ],
    routingPattern: 'agsi_entsoe_cross_commodity_lagebild',
  },
  {
    capability: 'settlement_a96_reconciliation',
    domain: 'settlement',
    abstractionLevel: 'deterministic_reconciliation',
    intent: 'settlement.a96.reconcile',
    keywords: [
      'a96',
      'reconcile',
      'reconciliation',
      'abgleich',
      'delta',
      'abweichung',
      'anlageid',
      'timeslice',
      'zeitfenster',
      'settlement',
    ],
    preferredActions: ['settlement.reconcileA96'],
    fallbackActions: ['settlement.prepareA96'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'settlementId',
        label: 'Settlement-ID',
        type: 'string',
        required: true,
      },
      {
        name: 'incomingRows',
        label: 'Eingehende A96-Zeilen',
        type: 'array',
        required: true,
      },
    ],
    risksAndNotes: [
      'Matching erfolgt strikt über anlageId/timeSlice, um Fehlzuordnungen zwischen Anlagen zu verhindern.',
      'Inbound-Payload bleibt transient und wird nicht als Settlement persistiert.',
    ],
    routingPattern: 'settlement_a96_reconciliation',
  },
  {
    capability: 'load_profile_stream_monitor',
    domain: 'edm-monitoring',
    abstractionLevel: 'deterministic_stream_diagnostics',
    intent: 'dashboard.load-profile-stream-monitor',
    keywords: [
      'lastgang',
      'lastgangdaten',
      'bewegungsstrom',
      'load profile',
      'stream monitor',
      'streamstatus',
      'anomaly class',
      'datenqualitätslücke',
      'forecast quality',
      'prozess-governance',
    ],
    preferredActions: ['dashboard-api.loadProfileStreamMonitor'],
    fallbackActions: [
      'edm.getTimeseriesSummary',
      'edm-validation.validate',
      'forecast-engine.evaluateQuality',
      'vdmi.findings',
    ],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'meloId',
        label: 'MeLo-ID',
        type: 'string',
        required: true,
      },
      {
        name: 'from',
        label: 'Startzeitpunkt',
        type: 'string',
        required: true,
      },
      {
        name: 'to',
        label: 'Endzeitpunkt',
        type: 'string',
        required: true,
      },
    ],
    risksAndNotes: [
      'Anomaly-Klassen sind strikt getrennt: dataQualityGap, realAnomaly, forecastProblem, processGovernanceBreak.',
      'Partial findings sind zulässig: fehlende Quellen werden über _errors transparent markiert.',
      'Read-only Aggregation; keine zusätzliche Persistenz oder parallele Validierungs-Engine.',
    ],
    routingPattern: 'load_profile_stream_monitor',
  },
  {
    capability: 'vdmi_role_boundary_governance',
    domain: 'vdmi-governance',
    abstractionLevel: 'governance_role_boundary',
    intent: 'vdmi_role_boundary_governance',
    keywords: [
      'rollen',
      'rolle',
      'rollengrenze',
      'schnittstellen',
      'zulässige aussagen',
      'projektträger nicht netzbetreiber',
      'ohne formales netzanschlussbegehren',
      'netzanschlussbegehren',
      '§17 enwg',
      '17 enwg',
      'arealnetzbetreiber',
      'darf keine netzanschlusszusage treffen',
      'netzanschlusszusage',
      'bedarfs',
      'antragsteller',
      'gatekeeper',
    ],
    preferredActions: ['vdmi.agentRole', 'vdmi.context'],
    fallbackActions: ['vdmi.agentRole', 'interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'agentId',
        label: 'Akteur-ID für Rollenprüfung',
        type: 'string',
        required: false,
      },
      {
        name: 'processType',
        label: 'Prozesstyp (z.B. grid-connection-governance)',
        type: 'string',
        required: false,
      },
    ],
    risksAndNotes: [
      'Ohne formales Netzanschlussbegehren keine verbindliche Kapazitäts- oder Übergabepunkt-Zusage.',
      'Projektträger/Business Owner ist nicht automatisch Netzbetreiber-Gatekeeper.',
      'Mehrrollen je Akteur task-spezifisch auswerten (nicht first-match).',
    ],
    routingPattern: 'vdmi_role_boundary_governance',
  },
  {
    capability: 'vdmi_asset_validation_governance',
    domain: 'vdmi-governance',
    abstractionLevel: 'governance_asset_validation',
    intent: 'vdmi_asset_validation_governance',
    keywords: [
      'asset validation',
      'asset-validierung',
      'asset validierung',
      'asset-prüfung',
      'asset pruefung',
      'assetklasse',
      'evidence',
      'evidenz',
      'nachweis',
      'beleg',
      'forbidden assumption',
      'verbotene annahme',
      'risk factors',
      'risikofaktoren',
      'grid-connection-asset-validation',
    ],
    preferredActions: ['vdmi.dossier', 'vdmi.negotiationTrace', 'vdmi.agentRole'],
    fallbackActions: ['vdmi.dossier', 'interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'taskId',
        label: 'Task-ID für Asset-Prüfung',
        type: 'string',
        required: true,
      },
      {
        name: 'processType',
        label: 'Prozesstyp (z.B. grid-connection-asset-validation)',
        type: 'string',
        required: false,
      },
    ],
    risksAndNotes: [
      'Asset-Validierung muss Evidenzlücken explizit ausweisen und darf keine fehlenden Nachweise erfinden.',
      'Risikofaktoren und verbotene Annahmen sind task-spezifisch aus der Matrix abzuleiten.',
      'Bei unvollständiger Evidenz nur zulässige Optionen mit Next Actions für V-Entscheidung ausgeben.',
    ],
    routingPattern: 'vdmi_asset_validation_governance',
  },
  {
    capability: 'vdmi_grid_connection_decision_governance',
    domain: 'vdmi-governance',
    abstractionLevel: 'governance_grid_connection_decision',
    intent: 'vdmi_grid_connection_decision_governance',
    keywords: [
      'anschlusszusage',
      'kapazitätszusage',
      'kapazitaetszusage',
      'übergabepunkt',
      'uebergabepunkt',
      'netzbetreiberentscheidung',
      'formales netzanschlussbegehren',
      '§17 enwg',
      '17 enwg',
      'belastbare zusage',
      'darf der netzbetreiber zusagen',
      'decision_blocked_pending_formal_request',
    ],
    preferredActions: ['vdmi.dossier', 'vdmi.negotiationTrace', 'vdmi.agentRole'],
    hitlPolicy: {
      criticalFlow: true,
      mode: 'mandatory_step_approval',
      criticalityClass: 'regulatory_commitment',
      stepActions: ['vdmi.dossier', 'vdmi.negotiationTrace', 'vdmi.agentRole'],
    },
    fallbackActions: ['vdmi.dossier', 'interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'taskId',
        label: 'Task-ID (optional, wird aus knownContext oder Matrix abgeleitet)',
        type: 'string',
        required: false,
      },
      {
        name: 'processType',
        label: 'Prozesstyp (z.B. grid-connection-governance)',
        type: 'string',
        required: false,
      },
      {
        name: 'matrixId',
        label: 'VDMI Matrix-ID (optional)',
        type: 'string',
        required: false,
      },
      {
        name: 'processId',
        label: 'VDMI Process-/Job-ID (optional)',
        type: 'string',
        required: false,
      },
    ],
    risksAndNotes: [
      'Ohne formales Netzanschlussbegehren (§17 EnWG) keine belastbare Anschluss-/Kapazitätszusage.',
      'Entscheidungskontext muss Evidenzlücken und verbotene Annahmen explizit enthalten.',
      'Wenn Task/V-Akteur nicht eindeutig auflösbar ist, mit interface-placeholder formal stoppen.',
    ],
    routingPattern: 'vdmi_grid_connection_decision_governance',
  },
  {
    capability: 'grid_operator_identity_resolution',
    domain: 'grid-operations',
    abstractionLevel: 'deterministic_lookup',
    intent: 'resolve_grid_operator_identity',
    keywords: [
      'netzbetreiber',
      'vnb',
      'dso',
      'stadtwerke',
      'bdew',
      'snb',
      'netzgebiet',
      'netzgebiet zuordnung',
      'netzgebiet klärung',
      'netzgebiet klaerung',
      'plz',
      'postleitzahl',
      'welcher netzbetreiber',
      'zuständig',
      'zustaendig',
      'vnb lookup',
      'netzbetreiber zuordnung',
      'netzbetreiber identität',
      'netzbetreiber identitaet',
      'firmenname',
      'anschlusskontext',
    ],
    preferredActions: [
      'grid-operations.marketPartners',
      'grid-operations.vnbLookup',
      'grid-operations.vnbLookupCodes',
    ],
    fallbackActions: ['grid-operations.marketPartners'],
    avoid: [
      'vdmi.dossier',
      'vdmi.agentRole',
      'grid-connection.validate',
      'query.ask',
      'query.askLearned',
    ],
    requiredInputs: [
      {
        name: 'query',
        label: 'Standort, PLZ, Ort, Firmenname oder Freitext',
        type: 'string',
        required: false,
      },
      {
        name: 'bdew',
        label: 'BDEW-Code (13-stellig)',
        type: 'string',
        required: false,
      },
      {
        name: 'city',
        label: 'Ort / Stadt',
        type: 'string',
        required: false,
      },
      {
        name: 'companyName',
        label: 'Firmenname / Unternehmensname',
        type: 'string',
        required: false,
      },
    ],
    risksAndNotes: [
      'Bei mehrdeutigen Treffern Top-3 Kandidaten vergleichen.',
      'Firmenname → zuerst marketPartners (query: name), dann vnbLookup mit gefundenem BDEW/Ort.',
      'PLZ/Ort → vnbLookup mit city-Parameter; BDEW-Code → vnbLookup mit bdew-Parameter.',
      'Reine Identitäts-/Netzgebiet-Anfragen nicht in VDMI oder grid-connection.validate routen.',
      'Fehlende Evidenz → interface-placeholder.markGap mit missing_lookup_evidence; kein Governance-Workflow.',
    ],
    routingPattern: 'vnb_identity_resolution',
  },
  {
    capability: 'inhouse_timeseries_analysis',
    domain: 'inhouse',
    abstractionLevel: 'domain_workflow',
    intent: 'inhouse_timeseries_analysis',
    keywords: ['inhouse', 'csv', 'upload', 'datasource', 'messwerte', 'lastprofil'],
    preferredActions: ['datasource-cache.query', 'in-memory-join.meteringSpotCost'],
    fallbackActions: ['datasource-cache.query'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'sourceId',
        label: 'Inhouse-Datasource',
        type: 'string',
        required: true,
      },
    ],
    risksAndNotes: [
      'Inhouse-Daten niemals über generische SQL-/Query-Tools abfragen.',
      'Aggregation/Join in-memory durchführen.',
    ],
    routingPattern: 'inhouse_datasource_cache_query',
  },
  {
    capability: 'mastr_asset_inventory',
    domain: 'assets',
    abstractionLevel: 'aggregated_service',
    intent: 'mastr_asset_inventory',
    keywords: [
      'mastr',
      'anlage',
      'anlagen',
      'pv',
      'wind',
      'speicher',
      'redispatch',
      'fernsteuerbarkeit',
    ],
    preferredActions: [
      'grid-operations.marketPartners',
      'grid-operations.vnbLookup',
      'assets.solar',
    ],
    fallbackActions: ['assets.all'],
    avoid: ['oep.query'],
    requiredInputs: [
      {
        name: 'query',
        label: 'Betreiber / Region',
        type: 'string',
        required: true,
      },
    ],
    risksAndNotes: [
      'Betriebsstatus und Netzbetreiberprüfstatus getrennt behandeln.',
      'OEP ist für reale Assetlisten sekundär gegenüber MaStR.',
    ],
    routingPattern: 'mastr_primary_asset_lookup',
  },
  {
    capability: 'oep_research_dataset_discovery',
    domain: 'oep',
    abstractionLevel: 'raw_data',
    intent: 'oep_research_dataset_discovery',
    keywords: ['oep', 'open energy platform', 'szenario', 'tyndp', 'nep'],
    preferredActions: ['oep.energyTables', 'oep.search', 'oep.query'],
    fallbackActions: ['oep.listSchemas', 'oep.listTables', 'oep.getTableMeta'],
    avoid: [],
    requiredInputs: [
      {
        name: 'q',
        label: 'Suchbegriff',
        type: 'string',
        required: false,
      },
    ],
    risksAndNotes: [
      'OEP-Daten als Szenario-/Forschungsquelle behandeln, nicht als Primärquelle für Assets.',
    ],
    routingPattern: 'oep_discovery_chain',
  },
  {
    capability: 'financier_due_diligence_assessment',
    domain: 'finance-agent',
    abstractionLevel: 'regulatory_finance_due_diligence',
    intent: 'financier_due_diligence_assessment',
    keywords: [
      'due diligence',
      'risk assessment',
      'kreditausschuss',
      'credit committee',
      'bankability',
      'condition precedent',
      'financier',
      'finanzierer',
      'vorläufiges risk assessment',
    ],
    preferredActions: ['finance-agent.analyze'],
    hitlPolicy: {
      criticalFlow: true,
      mode: 'mandatory_step_approval',
      criticalityClass: 'financial_commitment',
      stepActions: ['finance-agent.analyze'],
    },
    fallbackActions: ['finance-agent.analyze', 'interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'query',
        label: 'Due-Diligence-Frage',
        type: 'string',
        required: true,
      },
    ],
    risksAndNotes: [
      'Antworten müssen evidenzgebunden bleiben (keine erfundenen regulatorischen Fakten).',
      'Unsicherheiten/Annahmen explizit als vorläufig markieren (Condition-Precedent-Logik).',
      'Bei fehlender Evidenz sind Nachweise konkret anzufordern statt auf missing-interface zu fallen.',
    ],
    routingPattern: 'financier_due_diligence_assessment',
  },
  {
    capability: 'vnb_kpi_benchmark_comparison',
    domain: 'finance-agent',
    abstractionLevel: 'aggregated_kpi_comparison',
    intent: 'vnb_kpi_benchmark_comparison',
    keywords: [
      'benchmark',
      'vergleich',
      'potenzialvergleich',
      'nachbar',
      'wettbewerber',
      'kpi',
      'anschlussdauer',
      'digitalisierungsindex',
      'umsetzungsquote',
      'ewk',
    ],
    preferredActions: [
      'grid-operations.marketPartners',
      'ewk-monitoring.benchmarkVnb',
      'grid-operations.vnbLookup',
      'assets.all',
    ],
    fallbackActions: ['grid-operations.marketPartners', 'ewk-monitoring.benchmarkVnb'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      {
        name: 'vnb1Name',
        label: 'First VNB Name',
        type: 'string',
        required: true,
      },
      {
        name: 'vnb2Name',
        label: 'Second VNB Name',
        type: 'string',
        required: true,
      },
      {
        name: 'comparisonDimensions',
        label: 'Comparison Dimensions',
        type: 'array',
        items: 'string',
        default: ['anschlussdauer', 'digitalisierungsindex', 'umsetzungsquote'],
        required: false,
      },
    ],
    risksAndNotes: [
      'Both VNBs must be resolvable via marketPartners.',
      'EWK data is annual BNetzA source; may not reflect current operational status.',
      'Hard evidence only; no hypothetical synthesis unless explicitly requested.',
    ],
    routingPattern: 'vnb_kpi_benchmark_multi_step',
  },
  // ── Domain 1: Netzanschluss & BESS ───────────────────────────────────────
  {
    capability: 'ghost_asset_alert',
    domain: 'netzanschluss',
    keywords: ['ghost asset', 'ortsfremde anlage', 'mastr geo', 'eeg vergütung', 'netzgebiet'],
    preferredActions: ['ghost-asset-alert.scan', 'ghost-asset-alert.list', 'ghost-asset-alert.get'],
    fallbackActions: ['ghost-asset-alert.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
      { name: 'installations', label: 'Anlagen-Liste', type: 'array', required: true },
    ],
    risksAndNotes: [
      'Geo-Check basiert auf übergebenen Polygonen — VNB muss Netzgebiet als GeoJSON bereitstellen.',
    ],
    routingPattern: 'ghost_asset_scan',
  },
  {
    capability: 'bess_screening',
    domain: 'netzanschluss',
    keywords: ['bess', 'grossspeicher', 'netzanschluss evidence', 'speicheranschluss'],
    preferredActions: ['bess-screening.screen', 'bess-screening.list', 'bess-screening.get'],
    fallbackActions: ['bess-screening.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
    ],
    risksAndNotes: ['Nur verifizierte VNB-Evidenz zaehlt als VERIFIED — kein Marktpartner-Claim.'],
    routingPattern: 'bess_evidence_screen',
  },
  {
    capability: 'agnes_bottleneck',
    domain: 'netzanschluss',
    keywords: ['n-1', 'engpass', 'agnes', 'dynamisches netzentgelt', 'fnav portfolio'],
    preferredActions: ['agnes-bottleneck.assess', 'agnes-bottleneck.list', 'agnes-bottleneck.get'],
    fallbackActions: ['agnes-bottleneck.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
    ],
    risksAndNotes: [
      'N-1-Schwellwerte sind konfigurierbar; Standardwerte: 90% kritisch, 70% Warnung.',
    ],
    routingPattern: 'agnes_n1_assess',
  },
  {
    capability: 'capex_prioritization',
    domain: 'netzanschluss',
    keywords: ['capex', 'investitionspriorisierung', 'netzmassnahmen', 'c-level report'],
    preferredActions: [
      'capex-prioritization.analyze',
      'capex-prioritization.list',
      'capex-prioritization.get',
    ],
    fallbackActions: ['capex-prioritization.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
    ],
    risksAndNotes: [
      'Forbidden assumption field muss explizit ausgefuellt sein — keine hypothetischen CAPEX-Zahlen.',
    ],
    routingPattern: 'capex_prioritize',
  },
  {
    capability: 'connection_rejection_evidence',
    domain: 'netzanschluss',
    keywords: ['ablehnung', 'netzanschluss ablehnungsbegruendung', 'revisionspaket', 'audit hash'],
    preferredActions: [
      'connection-rejection-evidence.create',
      'connection-rejection-evidence.list',
      'connection-rejection-evidence.get',
    ],
    fallbackActions: ['connection-rejection-evidence.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
    ],
    risksAndNotes: [
      'SHA-256 auditHash ist deterministisch — Payload-Aenderungen invalidieren Hash.',
    ],
    routingPattern: 'rejection_evidence_create',
  },
  {
    capability: 'e2e_connection_check',
    domain: 'netzanschluss',
    keywords: ['e2e', 'anschluss koordination', 'multi-thread', 'pruefstrang'],
    preferredActions: [
      'e2e-connection-check.create',
      'e2e-connection-check.updateThread',
      'e2e-connection-check.list',
    ],
    fallbackActions: ['e2e-connection-check.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
    ],
    risksAndNotes: [
      'Alle 6 Standard-Threads muessen besetzt werden; COMPLETED erfordert alle Threads gruen.',
    ],
    routingPattern: 'e2e_check_coordinate',
  },
  // ── Domain 2: fNAV & Flexibilitaet ────────────────────────────────────────
  {
    capability: 'fnav_commercial_hedging',
    domain: 'flexibilitaet',
    keywords: ['fnav', 'fna', 'abregelung', 'commercial risk', 'compensation liability'],
    preferredActions: [
      'fnav-commercial-hedging.createContract',
      'fnav-commercial-hedging.createScenario',
      'fnav-commercial-hedging.listContracts',
    ],
    fallbackActions: ['fnav-commercial-hedging.listContracts'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
    ],
    risksAndNotes: [
      'Compensation rates sind vertragsspezifisch — generische Defaultwerte nur als Naerung.',
    ],
    routingPattern: 'fnav_risk_calculate',
  },
  {
    capability: 'flexibilitaetskosten_raster',
    domain: 'flexibilitaet',
    keywords: ['flexibilitaetskosten', 'signaleprioritaeten', 'steuerbarkeit', 'redispatch kosten'],
    preferredActions: [
      'flexibilitaetskosten-raster.create',
      'flexibilitaetskosten-raster.list',
      'flexibilitaetskosten-raster.get',
    ],
    fallbackActions: ['flexibilitaetskosten-raster.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
    ],
    risksAndNotes: [
      'Signalprioritaeten 1-6 sind normativ — Abweichungen brauchen explizite Begruendung.',
    ],
    routingPattern: 'flex_cost_grid',
  },
  // ── Domain 3: Stammdaten & Reporting ─────────────────────────────────────
  {
    capability: 'nkp_reporting',
    domain: 'stammdaten',
    keywords: ['nkp', 'netzknotenpunkt', 'reporting', 'plausibilitaetspruefung', 'kpi'],
    preferredActions: ['nkp-reporting.importReport', 'nkp-reporting.list', 'nkp-reporting.get'],
    fallbackActions: ['nkp-reporting.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
    ],
    risksAndNotes: ['Plausibilitaetspruefungen sind regelbasiert — Schwellwerte konfigurierbar.'],
    routingPattern: 'nkp_import_analyze',
  },
  {
    capability: 'reporting_governance',
    domain: 'stammdaten',
    keywords: ['governance', 'datenquelle', 'fabric', 'onelake', 'berichtswesen maturity'],
    preferredActions: [
      'reporting-governance.check',
      'reporting-governance.list',
      'reporting-governance.get',
    ],
    fallbackActions: ['reporting-governance.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
    ],
    risksAndNotes: [
      'Maturity-Score 0-100: >=80 = GOVERNED/AUTOMATED, <40 = sofortiger Handlungsbedarf.',
    ],
    routingPattern: 'reporting_governance_check',
  },
  // ── Domain 4: Systemwechsel & Assessment ─────────────────────────────────
  {
    capability: 'reinvest_signal',
    domain: 'asset_management',
    keywords: ['reinvest', 'aregv fotojahr', 'wartungslog', 'scada', 'investitionssignal'],
    preferredActions: ['reinvest-signal.analyze', 'reinvest-signal.list', 'reinvest-signal.get'],
    fallbackActions: ['reinvest-signal.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
    ],
    risksAndNotes: [
      'Fotojahr 2026 hat Bonus-Scoring — Eintraege nahe 2026 werden bevorzugt klassifiziert.',
    ],
    routingPattern: 'reinvest_classify',
  },
  {
    capability: 'vnb_100_tage_assessment',
    domain: 'asset_management',
    keywords: ['100 tage', 'quick assessment', 'vnb bewertung', 'kpi benchmark', 'roi modell'],
    preferredActions: [
      'vnb-100-tage-assessment.assess',
      'vnb-100-tage-assessment.list',
      'vnb-100-tage-assessment.get',
    ],
    fallbackActions: ['vnb-100-tage-assessment.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
    ],
    risksAndNotes: ['Alle 6 Domains muessen bewertet werden fuer vollstaendigen ROI-Report.'],
    routingPattern: 'vnb_quick_assess',
  },
  {
    capability: 'altdaten_assessment',
    domain: 'asset_management',
    keywords: ['altdaten', 'migration', 'fit-to-template', 'sap', 'erp', 'fit gap'],
    preferredActions: [
      'altdaten-assessment.assess',
      'altdaten-assessment.list',
      'altdaten-assessment.get',
    ],
    fallbackActions: ['altdaten-assessment.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
      { name: 'deviations', label: 'Abweichungsliste', type: 'array', required: true },
    ],
    risksAndNotes: ['BLOCKING-Gaps muessen vor Migrationsfreigabe geschlossen sein.'],
    routingPattern: 'altdaten_migration_assess',
  },
  {
    capability: 'automatisierungsradar',
    domain: 'asset_management',
    keywords: [
      'automatisierung',
      'prozesskettenanalyse',
      'quick win',
      'manual handoff',
      'automation radar',
    ],
    preferredActions: [
      'automatisierungsradar.analyze',
      'automatisierungsradar.list',
      'automatisierungsradar.get',
    ],
    fallbackActions: ['automatisierungsradar.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
      { name: 'steps', label: 'Prozessschritte', type: 'array', required: true },
    ],
    risksAndNotes: ['Impact/Effort 1-10 Skala: >=6 = HIGH; Quadrant QUICK_WIN = sofort umsetzen.'],
    routingPattern: 'automation_radar_analyze',
  },
  // ── Domain 5: Gasnetz & Waermeplanung ─────────────────────────────────────
  {
    capability: 'gasnetz_waermeplanung',
    domain: 'gasnetz',
    keywords: ['gasnetz', 'waermeplanung', 'wpg', 'stranded assets', 'totex', 'fernwaerme'],
    preferredActions: [
      'gasnetz-waermeplanung.reconcile',
      'gasnetz-waermeplanung.list',
      'gasnetz-waermeplanung.get',
    ],
    fallbackActions: ['gasnetz-waermeplanung.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
      { name: 'segments', label: 'Gasnetz-Segmente', type: 'array', required: true },
      { name: 'heatZones', label: 'Waermeplanungszonen', type: 'array', required: true },
    ],
    risksAndNotes: [
      'Stranded-Risk HIGH = sofortiger TOTEX-Investitionsstopp empfohlen. H2-Kandidaten nicht abreissen.',
    ],
    routingPattern: 'gas_heat_reconcile',
  },
  // ── Domain 6: VDMI & Regulatorik ─────────────────────────────────────────
  {
    capability: 'netzkoppelvertrag_workflow',
    domain: 'governance',
    keywords: ['netzkoppelvertrag', 'interconnection', 'dso tso', 'koppelvertrag workflow'],
    preferredActions: [
      'netzkoppelvertrag-workflow.create',
      'netzkoppelvertrag-workflow.updateStatus',
      'netzkoppelvertrag-workflow.list',
    ],
    fallbackActions: ['netzkoppelvertrag-workflow.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
    ],
    risksAndNotes: ['Technische Datenvollstaendigkeit >= 80% vor TECHNICALLY_APPROVED empfohlen.'],
    routingPattern: 'coupling_contract_workflow',
  },
  {
    capability: 'vdmi_portfolio_gatekeeping',
    domain: 'governance',
    keywords: [
      'vdmi',
      'portfolio gate',
      'investitionsfreigabe',
      'governance',
      'forbidden assumption',
    ],
    preferredActions: [
      'vdmi-portfolio-gatekeeping.gate',
      'vdmi-portfolio-gatekeeping.list',
      'vdmi-portfolio-gatekeeping.get',
    ],
    fallbackActions: ['vdmi-portfolio-gatekeeping.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
      { name: 'assetIds', label: 'Asset-IDs', type: 'array', required: true },
    ],
    risksAndNotes: ['REJECT bei BLOCKING-Violations — keine Umgehung ohne explizite Ausnahme.'],
    routingPattern: 'vdmi_gate_check',
  },
  {
    capability: 'vdmi_governance_templates',
    domain: 'governance',
    keywords: [
      'raci',
      'vdmi vorlage',
      'governance template',
      'rollenmatrix',
      'interface definition',
    ],
    preferredActions: [
      'vdmi-governance-templates.instantiate',
      'vdmi-governance-templates.listBaseTemplates',
      'vdmi-governance-templates.listInstances',
    ],
    fallbackActions: ['vdmi-governance-templates.listBaseTemplates'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
      { name: 'templateType', label: 'Template-Typ', type: 'string', required: true },
    ],
    risksAndNotes: [
      'Rollenbesetzung ueber roleAssignments — anonymisierte Basismatrizen enthalten keine Namen.',
    ],
    routingPattern: 'governance_template_instantiate',
  },
  {
    capability: 'regulatorische_entgeltlogik',
    domain: 'regulatorik',
    keywords: [
      'entgeltlogik',
      'netzentgelt',
      'aregv',
      'stromnev',
      '14a',
      'tarifversionen',
      'billing rules',
    ],
    preferredActions: [
      'regulatorische-entgeltlogik.registerRuleSet',
      'regulatorische-entgeltlogik.getActive',
      'regulatorische-entgeltlogik.list',
    ],
    fallbackActions: ['regulatorische-entgeltlogik.list'],
    avoid: ['query.ask'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber ID', type: 'string', required: true },
    ],
    risksAndNotes: [
      'Test Cases muessen 100% passen vor Produktionseinsatz — allPassed=false = Blocking.',
    ],
    routingPattern: 'tariff_rule_register',
  },
  // ── Domain 7: Entscheidungsrahmung (SCQA) ─────────────────────────────────
  {
    capability: 'scqa_decision_framing',
    domain: 'governance',
    abstractionLevel: 'problem_framing',
    intent: 'decision-frame.create',
    secondaryIntents: [
      'decision-frame.generateStarter',
      'decision-frame.get',
      'decision-frame.list',
    ],
    keywords: [
      'entscheidungsrahmen',
      'problemrahmen',
      'situation',
      'komplikation',
      'complication',
      'kernfrage',
      'transformation',
      'framing',
      'ausgangslage',
      'scqa',
      'decision frame',
      'shared situation picture',
      'entscheidung rahmen',
      'kontext rahmen',
      'transformationsdruck',
      'handlungsbedarf',
    ],
    preferredActions: [
      'decision-frame.generateStarter',
      'decision-frame.create',
      'decision-frame.list',
      'decision-frame.get',
    ],
    fallbackActions: ['decision-frame.list'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      { name: 'situation', label: 'Aktuelle Ausgangslage', type: 'string', required: true },
      {
        name: 'complication',
        label: 'Transformation / Druck / Constraint',
        type: 'string',
        required: true,
      },
    ],
    risksAndNotes: [
      'SCQA-Frames sind Entscheidungsrahmen, keine verbindlichen Fakten — immer mit Quelldaten validieren.',
      'generateStarter erfordert LLM-Konfiguration; faellt ohne GEMINI_API_KEY auf leere Platzhalter zurueck.',
      'Answer-Block bewusst offen lassen bis Analyse-Ergebnisse vorliegen — kein vorzeitiges Befuellen.',
    ],
    routingPattern: 'scqa_elicitation',
  },
  // ── Domain 8: Redispatch Readiness ────────────────────────────────────────
  {
    capability: 'file_ingest_monitor',
    domain: 'data-governance',
    abstractionLevel: 'deterministic_file_governance',
    intent: 'file-ingest-monitor.scan',
    keywords: [
      'file ingest',
      'file monitor',
      'csv monitor',
      'datei monitoring',
      'dateiimport',
      'importpfad',
      'schema version',
      'error folder',
      'fehlerordner',
      'stammdaten import',
      'datei governance',
      'ingest monitor',
      'file health',
      'datei freshness',
      'stale file',
      'importdatei',
    ],
    preferredActions: [
      'file-ingest-monitor.scan',
      'file-ingest-monitor.getStatus',
      'file-ingest-monitor.getFindings',
      'file-ingest-monitor.createMonitor',
      'file-ingest-monitor.listMonitors',
    ],
    fallbackActions: ['file-ingest-monitor.listMonitors'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      { name: 'watchPath', label: 'Überwachter Dateipfad', type: 'string', required: true },
    ],
    risksAndNotes: [
      'file-ingest-monitor ist domain-neutral — keine Redispatch-Semantik im Monitor selbst.',
      'Schema-Validierung prüft nur Struktur (Delimiter, Spalten); fachliche Semantik bleibt beim Consumer.',
      'Error-Folder-Findings sind immer error-severity — blockieren nachgelagerte Abrechnungsschritte.',
    ],
    routingPattern: 'file_ingest_monitor',
  },
  {
    capability: 'redispatch_asset_register',
    domain: 'redispatch',
    abstractionLevel: 'deterministic_asset_projection',
    intent: 'redispatch-asset-register.createProjection',
    keywords: [
      'redispatch asset register',
      'asset projektion',
      'technische ressource',
      'steuerbare ressource',
      'co-location',
      'co location',
      'ressourcenzuordnung',
      'anlagenregister redispatch',
      'malo zuordnung redispatch',
      'melo zuordnung redispatch',
      'identifier konflikt',
      'asset beziehung',
      'steuergruppe redispatch',
    ],
    preferredActions: [
      'redispatch-asset-register.createProjection',
      'redispatch-asset-register.listProjections',
      'redispatch-asset-register.createRelationship',
      'redispatch-asset-register.listRelationships',
    ],
    fallbackActions: ['redispatch-asset-register.listProjections'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      { name: 'mastrId', label: 'MaStR-ID der Anlage', type: 'string', required: true },
    ],
    risksAndNotes: [
      'Das Register ist eine Projektion — keine zweite Stammdatenwahrheit. MaStR bleibt führend.',
      'RDAR_RESOURCE_MAPPING_MISSING bei fehlendem technischem Ressourcenbezug — kein Settlement möglich.',
      'Co-Location-Beziehungen müssen explizit registriert werden; MaStR kennt keine Co-Location.',
    ],
    routingPattern: 'redispatch_asset_register',
  },
  {
    capability: 'redispatch_data_governance',
    domain: 'redispatch',
    abstractionLevel: 'deterministic_process_governance',
    intent: 'redispatch-data-governance.evaluate',
    keywords: [
      'redispatch governance',
      'führender datenpfad',
      'source of record',
      'fristenklasse',
      'deadline klasse',
      'stammdaten owner',
      'owner klasse',
      'governance policy redispatch',
      'datenpfad governance',
      'abrechnungsfrist redispatch',
      'owner zuweisung',
      'prozesskalender',
    ],
    preferredActions: [
      'redispatch-data-governance.evaluate',
      'redispatch-data-governance.createPolicy',
      'redispatch-data-governance.listPolicies',
      'redispatch-data-governance.listEvaluations',
    ],
    fallbackActions: ['redispatch-data-governance.listPolicies'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      { name: 'dataClass', label: 'Datenklasse', type: 'string', required: true },
      { name: 'processId', label: 'Prozess-ID', type: 'string', required: true },
    ],
    risksAndNotes: [
      'RDG_DEADLINE_MISSED hat severityOnMiss aus der Policy — kann blocking oder warning sein.',
      'Ohne passende Policy gibt es immer RDG_GOVERNANCE_POLICY_MISSING (error) — kein stilles Durchrauschen.',
      'redispatch-data-governance konsumiert file-ingest-monitor Status — beide Services müssen laufen.',
    ],
    routingPattern: 'redispatch_process_governance',
  },
  {
    capability: 'redispatch_settlement_sandbox',
    domain: 'redispatch',
    abstractionLevel: 'deterministic_settlement_simulation',
    intent: 'redispatch-settlement-sandbox.createScenario',
    keywords: [
      'settlement sandbox',
      'abrechnungsszenario',
      'settlement szenario',
      'redispatch szenario',
      'ausfallarbeit kalkulation',
      'redispatch kalkulation',
      'kwh eur szenario',
      'szenario abrechnung',
      'curtailment szenario',
      'einspeisemanagement abrechnung',
      'redispatch abrechnung variante',
    ],
    preferredActions: [
      'redispatch-settlement-sandbox.createScenario',
      'redispatch-settlement-sandbox.reconcile',
      'redispatch-settlement-sandbox.listScenarios',
      'redispatch-settlement-sandbox.getScenario',
    ],
    fallbackActions: ['redispatch-settlement-sandbox.listScenarios'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber-ID', type: 'string', required: true },
      { name: 'periodStart', label: 'Abrechnungsperiode Start', type: 'string', required: true },
      { name: 'periodEnd', label: 'Abrechnungsperiode Ende', type: 'string', required: true },
    ],
    risksAndNotes: [
      'Szenarien sind immutable nach Reconcile — neues Szenario für geänderte Inputs anlegen.',
      'inputHash verhindert doppelte Szenarien für gleiche Inputs + Policy-Version.',
      'RDSS_MISSING_DATAPOINT_EVIDENCE wenn settlement.a96Reconcile nicht erreichbar — upstream prüfen.',
    ],
    routingPattern: 'redispatch_settlement_sandbox',
  },
  // ── Domain 9: Non-VDMI Answer Dossier Domains ─────────────────────────────
  {
    capability: 'edm_customer_moveout_billing_evidence',
    domain: 'edm-customer-service',
    abstractionLevel: 'read_only_evidence_briefing',
    intent: 'edm_customer_moveout_billing_evidence',
    keywords: [
      'auszug',
      'einzug',
      'schlusszählerstand',
      'schlusszaehlerstand',
      'edm-plausibilisierung',
      'abrechnungsfreigabe',
      'plausibilisierung',
      'zählerstandsmeldung',
      'zaehlerstandsmeldung',
      'lieferbeginn',
      'lieferende',
      'gpke',
      'schlusszähler',
      'schlusszaehler',
    ],
    preferredActions: [
      'interface-placeholder.markGap',
      'interface-placeholder.requestEvidence',
      'interface-placeholder.listGaps',
    ],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['vdmi.dossier', 'vdmi.agentRole', 'vdmi.negotiationTrace', 'query.ask', 'query.askLearned'],
    requiredInputs: [
      { name: 'role', label: 'Betroffene Rolle (Kundenservice / EDM / Abrechnung)', type: 'string', required: false },
    ],
    risksAndNotes: [
      'Kein plausibilisierter Schlusszählerstand darf ohne EDM-Freigabe als Faktum ausgegeben werden.',
      'Kommunikationsgrenzen zum Kunden sind rollenabhängig — Kundenservice darf nur freigegebene Angaben weitergeben.',
      'Abrechnungsfreigabe ist erst nach EDM-Plausibilisierung und Schlusszählerstand-Bestätigung zulässig.',
    ],
    routingPattern: 'edm_moveout_billing_evidence_dossier',
  },
  {
    capability: 'energy_sharing_prosumer_advisory',
    domain: 'energy-sharing',
    abstractionLevel: 'read_only_evidence_briefing',
    intent: 'energy_sharing_prosumer_advisory',
    keywords: [
      'prosumer',
      'energy sharing',
      'mieterstrom',
      'direktlieferung',
      'nachbarschaftsverkauf',
      'eigenversorgung',
      'marktrollen',
      'messkonzept',
      'bilanzierung',
      'allokation',
      'nap-wallet',
      '§42c',
      '42c enwg',
      'gemeinschaftliche gebäudeversorgung',
      'gemeinschaftliche gebaeudeversorgung',
    ],
    preferredActions: [
      'interface-placeholder.markGap',
      'interface-placeholder.requestEvidence',
      'interface-placeholder.listGaps',
    ],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['vdmi.dossier', 'vdmi.agentRole', 'query.ask', 'query.askLearned'],
    requiredInputs: [
      { name: 'role', label: 'Anfragende Rolle (Prosumer / Netzbetreiber / Berater)', type: 'string', required: false },
    ],
    risksAndNotes: [
      'Keine verbindliche Rechtsberatung — Energy Sharing und Mieterstrom unterliegen §42c EnWG und bedürfen Rechtsklärung.',
      'NAP-Wallet-Onboarding und externe Dispatch-Aktionen dürfen nicht automatisch ausgelöst werden.',
      'Marktrollen (Erzeuger, Verteiler, Letztverbraucher) müssen klar getrennt werden.',
    ],
    routingPattern: 'energy_sharing_prosumer_advisory_dossier',
  },
  {
    capability: 'redispatch_rcs_special_case_governance',
    domain: 'redispatch-rcs',
    abstractionLevel: 'read_only_evidence_briefing',
    intent: 'redispatch_rcs_special_case_governance',
    keywords: [
      'expost-nachweis',
      'expost nachweis',
      'expost-evidence',
      'expost evidence',
      'expost',
      'rcs-sonderfall',
      'rcs sonderfall',
      'rcs-regelkatalog',
      'rcs regelkatalog',
      'vergütungszusage',
      'verguetungszusage',
      'redispatch-koordination',
      'redispatch-assetregister',
      'redispatch assetregister',
      'settlement-risiko',
      'settlement risiko',
    ],
    preferredActions: [
      'interface-placeholder.markGap',
      'interface-placeholder.requestEvidence',
      'interface-placeholder.listGaps',
    ],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: [
      'vdmi.dossier', 'vdmi.agentRole', 'vdmi.negotiationTrace',
      'grid-connection.fnavValidate', 'query.ask', 'query.askLearned',
    ],
    requiredInputs: [
      { name: 'mastrId', label: 'MaStR-ID der Anlage', type: 'string', required: false },
      { name: 'processType', label: 'Prozesstyp (Redispatch-2.0 / RCS / Expost)', type: 'string', required: false },
    ],
    risksAndNotes: [
      'Keine Vergütungszusage ohne validierten Expost-Nachweis.',
      'Sonderfall-Einordnung (Redispatch-2.0 / RCS / Expost-Nachklärung) ist Evidence-abhängig — ohne vollständigen Assetregister-Eintrag bleibt sie offen.',
      'Settlement-Risiko darf nur nach Reconcile-Ergebnis aus dem Settlement-Sandbox quantifiziert werden.',
    ],
    routingPattern: 'redispatch_rcs_special_case_governance_dossier',
  },
  {
    capability: 'datasource_registry_classification_governance',
    domain: 'datasource-governance',
    abstractionLevel: 'read_only_evidence_briefing',
    intent: 'datasource_registry_classification_governance',
    keywords: [
      'datasource registry',
      'datasource-registry',
      'datenquellenbestand',
      'datasource-classifier',
      'datasource-watcher',
      'datasource-discovery',
      'datasource-cache',
      'cache-status',
      'datenquelle',
      'ingest-registry',
      'datenquellen-registry',
    ],
    preferredActions: [
      'interface-placeholder.markGap',
      'interface-placeholder.requestEvidence',
      'interface-placeholder.listGaps',
    ],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['vdmi.dossier', 'vdmi.agentRole', 'query.ask', 'query.askLearned'],
    requiredInputs: [
      { name: 'sourceId', label: 'Datenquellen-ID oder -Name', type: 'string', required: false },
    ],
    risksAndNotes: [
      'Keine produktive Ingest-, Watcher-, Refresh- oder Schreibaktion ohne explizite Freigabe.',
      'Cache-Status und Klassifizierung sind read-only — Datenbasis erst nach vollständiger Governance-Freigabe für Netzplanung oder Abrechnung nutzen.',
    ],
    routingPattern: 'datasource_registry_classification_governance_dossier',
  },
  {
    capability: 'hitl_role_based_evidence_request',
    domain: 'hitl',
    abstractionLevel: 'read_only_evidence_briefing',
    intent: 'hitl_role_based_evidence_request',
    keywords: [
      'human-in-the-loop',
      'human in the loop',
      'ursprungssession',
      'persona-inbox',
      'persona inbox',
      'webhook-ausloesung',
      'webhook-auslosung',
      'hitl-nachforderung',
      'hitl nachforderung',
      'hitl-nachforderungen',
      'rollenbasierte evidence',
      'evidence-anforderung',
    ],
    preferredActions: [
      'interface-placeholder.markGap',
      'interface-placeholder.requestEvidence',
      'interface-placeholder.listGaps',
    ],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: [
      'vdmi.dossier', 'vdmi.agentRole',
      'notification.dispatch', 'notification.dispatchHitlApproval',
      'query.ask', 'query.askLearned',
    ],
    requiredInputs: [
      { name: 'role', label: 'Anfragende Rolle / Persona', type: 'string', required: false },
    ],
    risksAndNotes: [
      'Keine externe Nachricht, kein Webhook und kein Signal/Telegram ohne explizite Freigabe.',
      'Nur interne Vorbereitungslogik — externe Ausführung ausschließlich über separaten expliziten Pfad.',
      'Ursprungssession wird nur informiert, nicht direkt beschrieben.',
    ],
    routingPattern: 'hitl_role_based_evidence_request_dossier',
  },
  {
    capability: 'evidence_grounding_confidence_audit',
    domain: 'answer_evidence',
    abstractionLevel: 'read_only_evidence_confidence_audit',
    intent: 'dashboard-api.evidenceGroundingConfidenceAudit',
    keywords: [
      'confidence audit',
      'grounding',
      'evidence grounding',
      'quellenklasse',
      'quellenklassen',
      'scope filter',
      'scope-filter',
      'tool ausfall',
      'toolausfall',
      'netzbetreiber bestaetigung',
      'netzbetreiber bestätigung',
      'vorpruefung',
      'vorprüfung',
      'scheinsicherheit',
      'unsicherheitsstatus',
      'confidence begruendung',
      'confidence begründung',
      'evidence confidence',
      'routing confidence',
    ],
    preferredActions: [
      'dashboard-api.evidenceGroundingConfidenceAudit',
      'capability-broker.recommend',
      'knowledge-rag.query',
      'datapoint.health',
      'vdmi.findings',
    ],
    fallbackActions: ['dashboard-api.evidenceGroundingConfidenceAudit'],
    avoid: [
      'hitl.create',
      'interface-placeholder.requestEvidence',
      'knowledge-rag.ingest',
      'query.ask',
      'query.askLearned',
      'personal-agent.execute',
    ],
    requiredInputs: [
      { name: 'domain', label: 'Fachdomain', type: 'string', required: false },
      { name: 'query', label: 'Audit-Frage / Antwortkontext', type: 'string', required: false },
      { name: 'scopeId', label: 'Scope-Filter', type: 'string', required: false },
      { name: 'gridOperatorId', label: 'Netzbetreiber-ID', type: 'string', required: false },
      { name: 'datasourceId', label: 'Datasource-ID', type: 'string', required: false },
      { name: 'datapointId', label: 'Datapoint-ID', type: 'string', required: false },
    ],
    risksAndNotes: [
      'dashboard-api.evidenceGroundingConfidenceAudit ist read-only und dossier-safe.',
      'Routing-Confidence und Evidence-Confidence sind getrennt; ein guter Broker-Match ist keine fachliche Evidenzsicherheit.',
      'Toolausfall, fehlender Scope oder fehlende Netzbetreiberbestaetigung werden als positive Follow-ups sichtbar und deckeln die Evidence-Confidence.',
      'Keine zweite Antwortpipeline, keine neue LLM-Ausfuehrung, keine HITL-/Placeholder-Erzeugung und keine RAG-Ingestion.',
    ],
    routingPattern: 'evidence_grounding_confidence_audit',
  },
  {
    capability: 'redispatch_call_data_quality_gate',
    domain: 'redispatch',
    abstractionLevel: 'read_only_call_quality_aggregator',
    intent: 'dashboard-api.redispatchCallQualityGate',
    keywords: [
      'redispatch abruf',
      'abrufprozess',
      'redispatch abrufprozess',
      'datenqualitaets-gate',
      'datenqualität gate',
      'datenqualitaet gate',
      'redispatch datenqualitaet',
      'redispatch datenqualität',
      'nullwerte',
      'fehlende prognose',
      'kontrollnachweis',
      'ausscheidende anlage',
      'monitoring verantwortung',
      'redispatch clearing',
      'abrechnungsgate',
      'redispatch abrechnungsgate',
    ],
    preferredActions: [
      'dashboard-api.redispatchCallQualityGate',
      'redispatch-expost.list',
      'dashboard-api.loadProfileStreamMonitor',
      'edm-validation.validate',
      'datapoint.health',
      'forecast-engine.evaluateQuality',
      'vdmi.findings',
    ],
    fallbackActions: ['dashboard-api.redispatchCallQualityGate'],
    avoid: [
      'settlement.prepareA96',
      'settlement.exportA96',
      'hitl.create',
      'query.ask',
      'query.askLearned',
      'personal-agent.execute',
    ],
    requiredInputs: [
      { name: 'gridOperatorId', label: 'Netzbetreiber-ID', type: 'string', required: false },
      { name: 'meloId', label: 'Messlokation', type: 'string', required: false },
      { name: 'maloId', label: 'Marktlokation', type: 'string', required: false },
      { name: 'from', label: 'Abruf-/Messwertfenster von', type: 'string', required: false },
      { name: 'to', label: 'Abruf-/Messwertfenster bis', type: 'string', required: false },
      { name: 'auditId', label: 'Redispatch Audit-ID', type: 'string', required: false },
    ],
    risksAndNotes: [
      'dashboard-api.redispatchCallQualityGate ist read-only und dossier-safe.',
      'Fehlende Stammdaten, MeLo/MaLo, Lastgang-, Forecast-, Kontroll- oder Monitoring-Evidenz wird als positive Follow-up-Luecke sichtbar.',
      'Keine zweite Redispatch-Engine, keine Settlement-/A96-Schreibpfade, keine HITL-Erstellung und keine operative Redispatch-Steuerung.',
    ],
    routingPattern: 'redispatch_call_data_quality_gate',
  },
  {
    capability: 'redispatch_readiness_gate',
    domain: 'redispatch',
    abstractionLevel: 'deterministic_operational_readiness_gate',
    intent: 'redispatch-readiness-gate.getStatus',
    keywords: [
      'redispatch readiness',
      'redispatch produktivreife',
      'redispatch betriebsbereit',
      'zugangsmatrix redispatch',
      'testabruf redispatch',
      'produktivnachweis redispatch',
      'stammdatentemplate redispatch',
      'abnahmefrist redispatch',
      'redispatch readiness gate',
      'redispatch onboarding gate',
      'redispatch operative bereitschaft',
    ],
    preferredActions: [
      'redispatch-readiness-gate.getStatus',
      'redispatch-readiness-gate.evaluate',
      'redispatch-readiness-gate.listRuns',
      'redispatch-readiness-gate.getRun',
    ],
    fallbackActions: ['redispatch-readiness-gate.getStatus'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      { name: 'processId', label: 'Redispatch-Prozess-ID', type: 'string', required: false },
    ],
    risksAndNotes: [
      'getStatus ist read-only und dossier-safe; evaluate schreibt nur einen internen Audit-Run.',
      'Produktivreife ist erst ready, wenn Zugangsmatrix, Testabruf und Produktivnachweis belastbar sind.',
      'Offene Fragen, Rollenluecken und Template-Drift bleiben als Warnungen im Gate sichtbar.',
    ],
    routingPattern: 'redispatch_readiness_gate',
  },
  {
    capability: 're4de_variable_grid_fee_layer3',
    domain: 're4de_grid_fees',
    abstractionLevel: 'deterministic_layer3_value_service',
    intent: 're4de-variable-grid-fee.getEvidence',
    keywords: [
      're4de',
      'variable grid fee',
      'variable grid-fee',
      'variables netzentgelt',
      'variable netzentgelte',
      'tariff sheet',
      'tarifblatt',
      'grid fee calculation',
      'netzentgelt berechnung',
      'datenraum',
      'data product',
      'taf-7 interval',
      'section14a module 3',
      '§14a module 3',
    ],
    preferredActions: [
      're4de-variable-grid-fee.getEvidence',
      're4de-variable-grid-fee.getCalculation',
      're4de-variable-grid-fee.calculate',
    ],
    fallbackActions: ['re4de-variable-grid-fee.getEvidence'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      { name: 'calculationId', label: 'Calculation ID', type: 'string', required: false },
      { name: 'tariffSheet', label: 'Variable grid-fee tariff sheet', type: 'object', required: false },
      { name: 'meteringInput', label: 'JSON interval metering input', type: 'object', required: false },
      { name: 'gridAreaId', label: 'Grid area ID', type: 'string', required: false },
      { name: 'section14aConfig', label: '§14a context', type: 'object', required: false },
    ],
    risksAndNotes: [
      'getEvidence and getCalculation are read-only and dossier-safe.',
      'calculate is non-consequential audit-write only; it must not write billing, settlement, MaKo or device-control state.',
      'This capability is Re4DE-aligned, not full DSP/EDC/SSI/VC compliance.',
      'Missing tariff sheet, grid area, metering intervals, timezone or §14a context should become positive follow-up evidence requests.',
    ],
    routingPattern: 're4de_variable_grid_fee_layer3',
  },
  {
    capability: 'battery_redispatch_special_gate',
    domain: 'redispatch',
    abstractionLevel: 'deterministic_storage_special_gate',
    intent: 'battery-redispatch-special-gate.getStatus',
    keywords: [
      'batteriespeicher redispatch',
      'speicher sondergate',
      'redispatch speicher sondergate',
      'malo speicher',
      'melo speicher',
      'positive redispatch',
      'negative redispatch',
      'lastaufnahme',
      'einspeisung',
      'testabruf',
      'steuerbarkeitsrichtung',
      'clearing speicher',
      'abrechnung speicher',
      'battery redispatch special gate',
      'bess redispatch sondergate',
    ],
    preferredActions: [
      'battery-redispatch-special-gate.getStatus',
      'battery-redispatch-special-gate.evaluate',
      'battery-redispatch-special-gate.listGates',
      'battery-redispatch-special-gate.getGate',
    ],
    fallbackActions: ['battery-redispatch-special-gate.getStatus'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      { name: 'gateId', label: 'Battery Redispatch Gate ID', type: 'string', required: false },
      { name: 'assetId', label: 'Speicher-Asset-ID', type: 'string', required: false },
      { name: 'maloDecision', label: 'MaLo/MeLo-Entscheidung', type: 'string', required: false },
      { name: 'meteringConceptId', label: 'Messkonzept-ID', type: 'string', required: false },
    ],
    risksAndNotes: [
      'getStatus ist read-only und dossier-safe; evaluate schreibt nur eine interne Gate-Bewertung.',
      'Keine Speichersteuerung, kein MaKo-Write, keine Abrechnung, kein Clearing und kein produktiver Redispatch-Trigger.',
      'BESS, EDM/Messkonzept, Flex, Redispatch Ex-Post, Settlement, Bilanzkreis, VDMI und HITL bleiben Quellsysteme und werden nur referenziert.',
      'Fehlende MaLo/MeLo-Rollen, Richtungen, Steuerbarkeitsrichtung oder Nachweise werden als positive Follow-ups sichtbar.',
    ],
    routingPattern: 'battery_redispatch_special_gate',
  },
  {
    capability: 'flexibility_conductor_role_model',
    domain: 'vdmi-governance',
    abstractionLevel: 'read_only_role_model_evidence',
    intent: 'flexibility-conductor-role-model.getStatus',
    keywords: [
      'flexibilitaetsdirigent',
      'flexibilitätsdirigent',
      'flexibilitaetsorchestrierung',
      'flexibilitätsorchestrierung',
      'fahrplanmanagement',
      'steuerbefehl',
      'steuerbox',
      'softwareueberwachung',
      'softwareüberwachung',
      'flexibler netzanschluss',
      'niederspannung',
      'assetmanagement',
      'regulierungsbewertung',
      'raci',
      'entscheidungsrechte',
      'eskalationspfad',
      'rollenmodell flexibilitaet',
      'role model flexibility',
    ],
    preferredActions: [
      'flexibility-conductor-role-model.getStatus',
      'flexibility-conductor-role-model.evaluate',
      'flexibility-conductor-role-model.listModels',
      'flexibility-conductor-role-model.getModel',
    ],
    fallbackActions: ['flexibility-conductor-role-model.getStatus'],
    avoid: ['query.ask', 'query.askLearned', 'personal-agent.execute'],
    requiredInputs: [
      { name: 'processId', label: 'Flexibilitaetsprozess-ID', type: 'string', required: false },
      { name: 'assetScopeId', label: 'Flex-Asset-Scope-ID', type: 'string', required: false },
    ],
    risksAndNotes: [
      'getStatus ist read-only und dossier-safe; evaluate schreibt nur ein internes Rollenmodell-Evidence-Objekt.',
      'Bestehende Flex-, Grid-, Finance-, VDMI-, HITL- und Presentation-Actions bleiben Quellreferenzen und werden nicht durch Dossier-Hydration ausgefuehrt.',
      'Keine Steuerbefehle, Device-Status-Updates, Dispatch-Aktivierung, HITL-Freigabe, MaKo-, Settlement- oder Billing-Writes.',
      'Fehlende Entscheidungsrechte, Steuergrenzen, Monitoring-/Commercial-Owner oder Eskalationspfade werden als positive Follow-ups sichtbar.',
    ],
    routingPattern: 'flexibility_conductor_role_model',
  },
  {
    capability: 'knowledge_continuity_governance_gate',
    domain: 'vdmi-governance',
    abstractionLevel: 'read_only_knowledge_continuity_evidence',
    intent: 'knowledge-continuity-governance-gate.getStatus',
    keywords: [
      'wissenssicherung',
      'prozesskontinuitaet',
      'prozesskontinuität',
      'rollenwechsel',
      'uebergabedokument',
      'übergabedokument',
      'hauptordner',
      'berechtigungsowner',
      'permission owner',
      'gastzugriff',
      'adminrechte',
      'loeschfrist',
      'löschfrist',
      'teams',
      'loop',
      'sharepoint',
      'it-abnahme',
      'knowledge continuity',
      'governance gate',
    ],
    preferredActions: [
      'knowledge-continuity-governance-gate.getStatus',
      'knowledge-continuity-governance-gate.evaluate',
      'knowledge-continuity-governance-gate.listGates',
      'knowledge-continuity-governance-gate.getGate',
    ],
    fallbackActions: ['knowledge-continuity-governance-gate.getStatus'],
    avoid: ['query.ask', 'query.askLearned', 'personal-agent.execute'],
    requiredInputs: [
      { name: 'criticalProcessId', label: 'Wissenskritische Prozess-ID', type: 'string', required: false },
      { name: 'gateId', label: 'Governance Gate ID', type: 'string', required: false },
    ],
    risksAndNotes: [
      'getStatus ist read-only und dossier-safe; evaluate schreibt nur ein internes Governance-Evidence-Objekt.',
      'Bestehende VDMI-, Evidence-, Interface-Placeholder-, HITL- und Presentation-Actions bleiben Quellreferenzen und werden nicht durch Dossier-Hydration ausgefuehrt.',
      'Keine Teams-/SharePoint-/Loop-/IAM-Connectoren, keine Permission-, Admin-, Gastzugangs- oder Retention-Mutation, keine HITL-Freigabe.',
      'Fehlende Hauptordner, Owner, Uebergabedokumente, Chat-/Mail-Grenzen, Retention oder IT-Abnahme werden als positive Follow-ups sichtbar.',
    ],
    routingPattern: 'knowledge_continuity_governance_gate',
  },
  {
    capability: 'investment_maturity_off_balance_gate',
    domain: 'investment-finance-governance',
    abstractionLevel: 'read_only_investment_gate_evidence',
    intent: 'investment-maturity-off-balance-gate.getStatus',
    keywords: [
      'investitionsreifegrad',
      'off-balance',
      'off balance',
      'externe finanzierung',
      'extern finanzierung',
      'finanzierungszusatzkosten',
      'zusatzkosten finanzierung',
      'regulatory return',
      'regulatorischer return',
      'asset-risiko',
      'asset risiko',
      'iso-risiko',
      'iso risiko',
      'prozessqualitaet',
      'prozessqualität',
      'netzspielraum',
      'entscheidungsforum',
      'investment maturity',
      'off-balance gate',
    ],
    preferredActions: [
      'investment-maturity-off-balance-gate.getStatus',
      'investment-maturity-off-balance-gate.evaluate',
      'investment-maturity-off-balance-gate.listGates',
      'investment-maturity-off-balance-gate.getGate',
    ],
    fallbackActions: ['investment-maturity-off-balance-gate.getStatus'],
    avoid: ['query.ask', 'query.askLearned', 'personal-agent.execute'],
    requiredInputs: [
      { name: 'investmentCaseId', label: 'Investment Case ID', type: 'string', required: false },
      { name: 'gateId', label: 'Off-Balance Gate ID', type: 'string', required: false },
    ],
    risksAndNotes: [
      'getStatus ist read-only und dossier-safe; evaluate schreibt nur ein internes Evidence-/Readiness-Objekt.',
      'Bestehende Investment-, Finance-, Decision-Frame-, VDMI-, HITL- und Presentation-Actions bleiben Quellreferenzen und werden nicht durch Dossier-Hydration ausgefuehrt.',
      'Keine Finanzierungsfreigabe, keine Bilanzierungsentscheidung, keine Off-Balance-Rechtsklassifikation, kein Investment-Plan-Write, keine HITL-Freigabe, keine Settlement-/Billing-/MaKo- oder Control-Writes.',
      'Fehlende Reifegrad-, Prozessqualitaets-, Kosten-, Return-, Asset-Risk-, ISO-Risk- oder Gremiennachweise werden als positive Follow-ups sichtbar.',
    ],
    routingPattern: 'investment_maturity_off_balance_gate',
  },
  {
    capability: 'gas_capacity_order_revision_gate',
    domain: 'gas-capacity-governance',
    abstractionLevel: 'read_only_gas_capacity_revision_evidence',
    intent: 'gas-capacity-order-revision-gate.getStatus',
    keywords: [
      'gaskapazitaetsbestellung',
      'gaskapazitätsbestellung',
      'jahresbestellung',
      'kapazitaetsbestellung',
      'kapazitätsbestellung',
      'gaskapazitaet',
      'gaskapazität',
      'kaltjahr',
      'milder winter',
      'industrie-rebound',
      'industrie rebound',
      'rlm rebound',
      'reversible rlm',
      'sicherheitsaufschlag',
      'netzkopplungspunkt',
      'nkp',
      'engpasshistorie',
      'druckflexibilitaet',
      'druckflexibilität',
      'wartungsfenster',
      'bestellbeschluss',
      'gas capacity order',
      'revision gate',
    ],
    preferredActions: [
      'gas-capacity-order-revision-gate.getStatus',
      'gas-capacity-order-revision-gate.evaluate',
      'gas-capacity-order-revision-gate.listRevisions',
      'gas-capacity-order-revision-gate.getRevision',
    ],
    fallbackActions: ['gas-capacity-order-revision-gate.getStatus'],
    avoid: ['query.ask', 'query.askLearned', 'personal-agent.execute'],
    requiredInputs: [
      { name: 'revisionId', label: 'Gas Capacity Revision ID', type: 'string', required: false },
      { name: 'orderYear', label: 'Bestelljahr', type: 'number', required: false },
      { name: 'gridOperatorId', label: 'Netzbetreiber', type: 'string', required: false },
    ],
    risksAndNotes: [
      'getStatus ist read-only und dossier-safe; evaluate schreibt nur ein internes Evidence-/Readiness-Objekt.',
      'Bestehende Gas-, Forecast-, Grid-, Finance-, VDMI- und Presentation-Actions bleiben Quellreferenzen und werden nicht durch Dossier-Hydration ausgefuehrt.',
      'Keine Gaskapazitaetsbestellung, keine Nominierung, keine Vertragsmutation, keine MaKo-/Settlement-/Billing-Writes, keine Drucksteuerung, keine Netzoperation, keine HITL-Freigabe.',
      'Fehlende Kaltjahr-, RLM-/Rebound-, Engpass-, NKP-, Entgelt-, Wartungs- oder Beschlussevidenz wird als positive Follow-ups sichtbar.',
    ],
    routingPattern: 'gas_capacity_order_revision_gate',
  },
  {
    capability: 'redispatch_special_case_gate',
    domain: 'redispatch',
    abstractionLevel: 'deterministic_special_case_gate',
    intent: 'redispatch-special-case-gate.evaluate',
    keywords: [
      'speicher redispatch',
      'eigenverbrauch redispatch',
      'co-location gate',
      'co location gate',
      'sonderfall gate',
      'special case gate',
      'steuerbarkeitsnachweis',
      'nichtverfügbarkeit redispatch',
      'nichtverfuegbarkeit redispatch',
      'abweichungstoleranz',
      'redispatch gate speicher',
      'bess redispatch gate',
      'eigenverbrauch gate',
    ],
    preferredActions: [
      'redispatch-special-case-gate.evaluate',
      'redispatch-special-case-gate.listRuns',
      'redispatch-special-case-gate.getRun',
    ],
    fallbackActions: ['redispatch-special-case-gate.listRuns'],
    avoid: ['query.ask', 'query.askLearned'],
    requiredInputs: [
      { name: 'mastrId', label: 'MaStR-ID der Anlage', type: 'string', required: true },
      { name: 'periodStart', label: 'Bewertungszeitraum Start', type: 'string', required: true },
      { name: 'periodEnd', label: 'Bewertungszeitraum Ende', type: 'string', required: true },
    ],
    risksAndNotes: [
      'Status insufficient_evidence wenn redispatch-asset-register oder assets-Service nicht erreichbar.',
      'RSCG_CONTROLLABILITY_MISSING ist blocking — Abrechnung nicht freigebbar ohne Steuerbarkeitsnachweis.',
      'Gate ist idempotent: gleiche Inputs + Policy ergeben gleiches Ergebnis; neuen Run für neue Evidence anlegen.',
    ],
    routingPattern: 'redispatch_special_case_gate',
  },

  // ── Domain Routes Registry gap-marker capabilities (answer-dossier-domain-routes.json) ──
  // These are declared-gap capabilities with no live implementation yet.
  // Routing is driven by the declarative registry; the catalog entry provides
  // the recommended plan (interface-placeholder.markGap) and metadata.

  {
    capability: 'edm_metering_concept_evidence',
    domain: 'edm',
    abstractionLevel: 'domain_gap_marker',
    intent: 'edm_metering_concept_evidence',
    keywords: ['mk40', 'mscons', 'messkonzept', 'edm metering', 'metering concept', 'edm plausibilisierung'],
    preferredActions: ['edm-messkonzept.list', 'edm-messkonzept.get', 'interface-placeholder.markGap'],
    fallbackActions: ['edm-messkonzept.list', 'interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned', 'vdmi.dossier'],
    requiredInputs: [],
    risksAndNotes: [
      'MSCONS/MK40 Messkonzept-Evidence nicht über VDMI-Asset-Validierungspfad ableiten.',
      'Listen-/Get-Hydration ist read-only; neue Messkonzepte nur bei explizit gelieferten Nutzerfakten oder Coverage-Seeds anlegen.',
    ],
    routingPattern: 'edm_metering_concept_evidence',
  },
  {
    capability: 'flex_forecast_bess_grid_operations_advisory',
    domain: 'forecast',
    abstractionLevel: 'domain_gap_marker',
    intent: 'flex_forecast_bess_grid_operations_advisory',
    keywords: ['bess', 'flexibilitätsprognose', 'flex forecast', 'battery energy storage', 'bess grid'],
    preferredActions: ['interface-placeholder.markGap', 'interface-placeholder.requestEvidence'],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned', 'vdmi.dossier'],
    requiredInputs: [],
    risksAndNotes: [
      'BESS/Flex-Forecast ist kein VDMI-Asset-Validierungskontext.',
      'Keine Schaltanweisung oder MW-Zusage ohne belastbare Forecast-Evidence.',
    ],
    routingPattern: 'flex_forecast_bess_grid_operations_advisory',
  },
  {
    capability: 'finance_nkp_capex_reinvest_governance',
    domain: 'finance',
    abstractionLevel: 'domain_gap_marker',
    intent: 'finance_nkp_capex_reinvest_governance',
    keywords: ['nkp', 'netzkostenpauschale', 'capex', 'reinvestitionsplanung', 'regulatorische kapitalkosten'],
    preferredActions: ['interface-placeholder.markGap', 'interface-placeholder.requestEvidence'],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned', 'vdmi.dossier'],
    requiredInputs: [],
    risksAndNotes: [
      'NKP/CAPEX-Governance nicht über VDMI-Asset-Validierungs- oder Netzanschluss-Pfade ableiten.',
    ],
    routingPattern: 'finance_nkp_capex_reinvest_governance',
  },
  {
    capability: 'bilanzkreis_slp_edm_operations',
    domain: 'edm',
    abstractionLevel: 'domain_gap_marker',
    intent: 'bilanzkreis_slp_edm_operations',
    keywords: ['bilanzkreis', 'bilanzgruppe', 'slp', 'standardlastprofil', 'fahrplanabgleich', 'bilanzkreisausgleich'],
    preferredActions: ['bilanzkreis.list', 'bilanzkreis.get', 'interface-placeholder.markGap'],
    fallbackActions: ['bilanzkreis.list', 'interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned', 'vdmi.dossier'],
    requiredInputs: [],
    risksAndNotes: [
      'Bilanzkreis-/SLP-Abweichungen nicht über VDMI-Governance-Pfade ableiten.',
      'Bilanzkreis-Hydration darf vorhandene Definitionen lesen; operative Berechnung/Schreibpfade brauchen explizite Eingaben.',
    ],
    routingPattern: 'bilanzkreis_slp_edm_operations',
  },
  {
    capability: 'connection_rejection_fnav_14a_evidence',
    domain: 'grid-operations',
    abstractionLevel: 'domain_gap_marker',
    intent: 'connection_rejection_fnav_14a_evidence',
    keywords: ['§14a', '14a enwg', 'anschlussablehnung', 'steuerbare verbrauchseinrichtung', 'connection rejection'],
    preferredActions: ['interface-placeholder.markGap', 'interface-placeholder.requestEvidence'],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned', 'vdmi.dossier'],
    requiredInputs: [],
    risksAndNotes: [
      '§14a-Anschlussablehnung ist kein §17-EnWG-Netzanschlussbegehren-Kontext.',
      'Evidence für Widerspruch muss technisch und regulatorisch getrennt dokumentiert werden.',
    ],
    routingPattern: 'connection_rejection_fnav_14a_evidence',
  },
  {
    capability: 'gasnetz_waermeplanung_assessment',
    domain: 'gas',
    abstractionLevel: 'domain_gap_marker',
    intent: 'gasnetz_waermeplanung_assessment',
    keywords: ['wärmeplanung', 'waermeplanung', 'gasnetz', 'kommunale wärmeplanung', 'gasinfrastruktur transformation'],
    preferredActions: ['interface-placeholder.markGap', 'interface-placeholder.requestEvidence'],
    fallbackActions: ['interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned', 'vdmi.dossier'],
    requiredInputs: [],
    risksAndNotes: [
      'Kommunale Wärmeplanung / Gasnetz-Transformation nicht über VDMI-Asset-Validierungspfade ableiten.',
    ],
    routingPattern: 'gasnetz_waermeplanung_assessment',
  },
  {
    capability: 'eeg_clawback_ewk_monitoring',
    domain: 'regulatory',
    abstractionLevel: 'domain_gap_marker',
    intent: 'eeg_clawback_ewk_monitoring',
    keywords: ['eeg clawback', 'eeg-clawback', 'clawback', 'ewk monitoring', 'eeg rückforderung', 'eeg rueckforderung'],
    preferredActions: ['ewk-monitoring.benchmarkVnb', 'interface-placeholder.markGap'],
    fallbackActions: ['ewk-monitoring.benchmarkVnb', 'interface-placeholder.markGap'],
    avoid: ['query.ask', 'query.askLearned', 'vdmi.dossier'],
    requiredInputs: [
      { name: 'vnbName', label: 'VNB-Name für EWK-Benchmark', type: 'string', required: false },
    ],
    risksAndNotes: [
      'EEG-Clawback-Monitoring und EWK-Bewertung nicht über VDMI-Governance-Pfade ableiten.',
      'EWK-Benchmark ist ein read-only Evidence-Pfad; EEG-Clawback-Rechnung bleibt separater, parameterpflichtiger Analysepfad.',
    ],
    routingPattern: 'eeg_clawback_ewk_monitoring',
  },
];

const GLOBAL_DO_NOT_USE = [
  {
    action: 'query.ask',
    reason:
      'Nur nutzen, wenn kein deterministischer oder domaenenspezifischer Pfad verfuegbar ist.',
  },
  {
    action: 'query.askLearned',
    reason:
      'Nur nutzen, wenn kein deterministischer oder domaenenspezifischer Pfad verfuegbar ist.',
  },
];

module.exports = {
  BROKER_SCHEMA_VERSION,
  CURATED_CAPABILITIES,
  INTERFACE_PLACEHOLDER_CAPABILITY,
  GLOBAL_DO_NOT_USE,
};
