const semanticDomains = [
  {
    id: 'metering',
    label: 'Metering Load Profile',
    department: 'Energiedatenmanagement',
    description: 'Zeitreihen aus Lastgang-, Verbrauchs- und Einspeisedaten.',
    indicators: {
      columnKeywords: [
        'zeit',
        'timestamp',
        'verbrauch',
        'consumption',
        'einspeisung',
        'feedin',
        'leistung',
        'lastgang',
        'bezug',
        'kwh',
      ],
      filenameTokens: ['metering', 'load', 'lastgang', 'profil', 'verbrauch', 'smartmeter'],
      requiredCapabilities: ['timeseries'],
      criticalFields: ['timeReference', 'consumptionKWh', 'feedInKWh'],
    },
    fieldProfiles: {
      timeReference: {
        aliases: ['timestamp', 'zeit', 'datum', 'datetime', 'zeitpunkt', 'zeitstempel'],
        expectedKinds: ['timestamp'],
      },
      consumptionKWh: {
        aliases: [
          'verbrauch',
          'bezug',
          'consumption',
          'consumptionkwh',
          'bezugkwh',
          'last',
          'verbrauchkwh',
        ],
        expectedKinds: ['float', 'integer'],
      },
      feedInKWh: {
        aliases: ['einspeisung', 'feedin', 'feed_in', 'export', 'einspeisungkwh'],
        expectedKinds: ['float', 'integer'],
      },
    },
    fixtureFile: 'tests/fixtures/metering_load_profile.csv',
    exampleQueries: [
      'Wie hoch ist der durchschnittliche Verbrauch pro Stunde?',
      'Wann ist die Einspeisung am höchsten?',
    ],
  },
  {
    id: 'grid-assets',
    label: 'Grid Assets',
    department: 'Asset Management / VNB',
    description:
      'Anlagenstammdaten für Netz- und Erzeugungsassets wie Trafostationen, Leitungen, Schaltanlagen und Kraftwerkseinheiten.',
    indicators: {
      columnKeywords: [
        'asset',
        'anlage',
        'anlagenid',
        'anlagenbetreiber',
        'assettyp',
        'trafo',
        'anschlusstrafo',
        'station',
        'kraftwerk',
        'erzeugung',
        'mastr',
        'pv',
        'photovoltaik',
        'leistung',
        'kwp',
        'spannung',
        'spannungsebene',
        'netzebene',
        'voltage',
        'install',
        'inbetriebnahme',
        'einspeisemanagement',
        'jahr',
        'standort',
        'typ',
        'technologie',
        'energieträger',
        'anschlussnetzbetreiber',
        'nettonennleistung',
      ],
      filenameTokens: [
        'grid',
        'assets',
        'netz',
        'anlagen',
        'anlagenliste',
        'pv',
        'photovoltaik',
        'trafo',
        'betriebsmittel',
        'kraftwerk',
        'kraftwerksliste',
        'erzeugung',
      ],
      requiredCapabilities: ['asset_catalog'],
      criticalFields: ['assetId', 'assetType', 'voltageLevel', 'installYear'],
    },
    fieldProfiles: {
      assetId: {
        aliases: [
          'assetid',
          'anlage',
          'anlagenid',
          'betriebsmittel',
          'trafoid',
          'mastr',
          'mastrnr',
          'stromerzeugungseinheit',
        ],
        expectedKinds: ['idlike', 'string'],
      },
      assetType: {
        aliases: [
          'type',
          'typ',
          'assettype',
          'assettyp',
          'anlagentyp',
          'technologie',
          'energieträger',
          'hauptbrennstoff',
          'stromerzeugung',
        ],
        expectedKinds: ['string'],
      },
      voltageLevel: {
        aliases: ['spannung', 'voltage', 'spannungsebene', 'netzebene', 'gridlevel'],
        expectedKinds: ['string'],
      },
      installYear: {
        aliases: [
          'install',
          'baujahr',
          'jahr',
          'commissioningyear',
          'inbetriebnahme',
          'jahrderinbetriebnahme',
        ],
        expectedKinds: ['integer'],
      },
    },
    fixtureFile: 'tests/fixtures/grid_assets.csv',
    exampleQueries: [
      'Wie viele Mittelspannungsanlagen wurden vor 2010 installiert?',
      'Welche Asset-Typen dominieren im Netzgebiet?',
    ],
  },
  {
    id: 'grid-incidents',
    label: 'Grid Incidents',
    department: 'Asset Management / VNB',
    description: 'Störungs- und Ereignisprotokolle für Assets und Netzsegmente.',
    indicators: {
      columnKeywords: [
        'incident',
        'stoer',
        'störung',
        'cause',
        'ursache',
        'duration',
        'dauer',
        'asset',
        'datum',
        'outage',
      ],
      filenameTokens: ['incident', 'stoerung', 'outage', 'netzereignis', 'gridfault'],
      requiredCapabilities: ['incident_log'],
      criticalFields: ['assetId', 'incidentDate', 'durationMin', 'cause'],
    },
    fieldProfiles: {
      assetId: {
        aliases: ['assetid', 'anlage', 'betriebsmittel', 'trafoid'],
        expectedKinds: ['idlike', 'string'],
      },
      incidentDate: {
        aliases: ['incidentdate', 'datum', 'receivedat', 'stoerungsdatum', 'ereigniszeit'],
        expectedKinds: ['timestamp'],
      },
      durationMin: {
        aliases: ['duration', 'dauer', 'dauermin', 'minuten'],
        expectedKinds: ['integer', 'float'],
      },
      cause: {
        aliases: ['cause', 'ursache', 'stoerungsursache', 'reason'],
        expectedKinds: ['string'],
      },
    },
    fixtureFile: 'tests/fixtures/grid_incidents.csv',
    exampleQueries: [
      'Welche Ursache tritt am häufigsten auf?',
      'Wie lange dauern Trafostörungen im Mittel?',
    ],
  },
  {
    id: 'redispatch-queue',
    label: 'Redispatch Queue',
    department: 'Energiedatenmanagement',
    description: 'Offene Redispatch- oder EinsMan-Anfragen mit Leistungs- und Statusdaten.',
    indicators: {
      columnKeywords: [
        'melo',
        'redispatch',
        'requested',
        'kw',
        'timestamp',
        'status',
        'anforderung',
        'leistung',
      ],
      filenameTokens: ['redispatch', 'queue', 'einsman', 'steuerung'],
      requiredCapabilities: ['timeseries_or_positional'],
      criticalFields: ['meloId', 'requestedKW', 'timeReference', 'status'],
    },
    fieldProfiles: {
      meloId: {
        aliases: ['melo', 'messlokation', 'meloid', 'messlokationsid'],
        expectedKinds: ['idlike', 'string'],
      },
      requestedKW: {
        aliases: ['requestedkw', 'anforderung', 'leistung', 'targetkw', 'angefordertkw'],
        expectedKinds: ['float', 'integer'],
      },
      timeReference: {
        aliases: ['timestamp', 'zeit', 'requesttime', 'zeitpunkt'],
        expectedKinds: ['timestamp'],
      },
      status: { aliases: ['status', 'state', 'queue'], expectedKinds: ['string'] },
    },
    fixtureFile: 'tests/fixtures/redispatch_queue.csv',
    exampleQueries: [
      'Wie viele Redispatch-Fälle sind noch offen?',
      'Welche Messlokationen haben die höchste angeforderte Leistung?',
    ],
  },
  {
    id: 'mastr-local',
    label: 'Local MaStR Units',
    department: 'VNB / Netzbetreiberprüfung',
    description: 'Lokale MaStR-Anlagenauszüge mit Typ, Leistung und Prüfstatus.',
    indicators: {
      columnKeywords: [
        'mastr',
        'see',
        'swe',
        'status',
        'leistung',
        'capacity',
        'unit',
        'typ',
        'netzbetreiber',
        'mastrnr',
        'nettonennleistung',
        'energieträger',
        'bundesland',
        'inbetriebnahmedatum',
        'erzeugungseinheit',
        'anlagenbetreiber',
      ],
      filenameTokens: ['mastr', 'lokal', 'units', 'anlagen'],
      requiredCapabilities: ['asset_catalog'],
      criticalFields: ['mastrId', 'unitType', 'capacityKWp', 'status'],
    },
    fieldProfiles: {
      mastrId: {
        aliases: ['mastr', 'mastrid', 'see', 'swe', 'san', 'einheit'],
        expectedKinds: ['idlike', 'string'],
      },
      unitType: { aliases: ['type', 'typ', 'unittype', 'einheitentyp'], expectedKinds: ['string'] },
      capacityKWp: {
        aliases: ['capacity', 'leistung', 'kwp', 'kw'],
        expectedKinds: ['float', 'integer'],
      },
      status: {
        aliases: ['status', 'betriebsstatus', 'netzbetreiberpruefung', 'pruefung'],
        expectedKinds: ['string'],
      },
    },
    fixtureFile: 'tests/fixtures/mastr_local_units.csv',
    exampleQueries: [
      'Wie viele Anlagen sind noch in Prüfung?',
      'Welche Einheitentypen dominieren lokal?',
    ],
  },
  {
    id: 'procurement',
    label: 'Energy Procurement',
    department: 'Energieeinkauf',
    description: 'Termin-, Spot- und Beschaffungspositionen mit Mengen, Preisen und Gegenparteien.',
    indicators: {
      columnKeywords: [
        'mwh',
        'eur',
        'counterparty',
        'gegenpartei',
        'delivery',
        'product',
        'produkt',
        'volume',
        'forward',
        'spot',
        'hedge',
        'preis',
        'referenz',
      ],
      filenameTokens: ['einkauf', 'procurement', 'portfolio', 'beschaffung', 'hedge'],
      requiredCapabilities: ['timeseries_or_positional'],
      criticalFields: ['timeReference', 'quantityMWh', 'priceEURperMWh'],
    },
    fieldProfiles: {
      timeReference: {
        aliases: [
          'delivery',
          'liefer',
          'period',
          'zeitraum',
          'quartal',
          'monat',
          'lieferzeitraum',
          'referenz',
        ],
        expectedKinds: ['date-range', 'timestamp', 'string'],
      },
      quantityMWh: {
        aliases: ['mwh', 'menge', 'volume', 'volumen', 'volumenmwh'],
        expectedKinds: ['float', 'integer'],
      },
      priceEURperMWh: {
        aliases: ['preis', 'eurmwh', 'price', 'euro', 'preiseurmwh'],
        expectedKinds: ['float', 'integer'],
      },
    },
    fixtureFile: 'tests/fixtures/procurement_portfolio.csv',
    exampleQueries: [
      'What is the average procurement price for Q2 2026?',
      'Which counterparty has the largest open position?',
    ],
  },
  {
    id: 'forecast-vs-actual',
    label: 'Forecast vs Actual',
    department: 'Energieeinkauf / EDM',
    description: 'Vergleich von Prognose- und Ist-Zeitreihen für Energievolumina.',
    indicators: {
      columnKeywords: [
        'forecast',
        'actual',
        'ist',
        'prognose',
        'mwh',
        'abweichung',
        'delta',
        'timestamp',
      ],
      filenameTokens: ['forecast', 'actual', 'prognose', 'vergleich', 'delta'],
      requiredCapabilities: ['timeseries_compare_actual_vs_forecast'],
      criticalFields: ['timeReference', 'forecastMWh', 'actualMWh'],
    },
    fieldProfiles: {
      timeReference: {
        aliases: ['timestamp', 'zeit', 'stunde', 'zeitpunkt'],
        expectedKinds: ['timestamp'],
      },
      forecastMWh: {
        aliases: ['forecast', 'prognose', 'plan', 'wartung', 'prognosemwh'],
        expectedKinds: ['float', 'integer'],
      },
      actualMWh: {
        aliases: ['actual', 'ist', 'realisierung', 'erzeugung', 'istmwh'],
        expectedKinds: ['float', 'integer'],
      },
    },
    fixtureFile: 'tests/fixtures/forecast_vs_actual.csv',
    exampleQueries: [
      'Wie groß ist die mittlere Prognoseabweichung?',
      'Zu welchen Stunden lag der Istwert über der Prognose?',
    ],
  },
  {
    id: 'billing-overview',
    label: 'Billing Overview',
    department: 'Abrechnung',
    description: 'Abrechnungsübersichten mit Perioden, Beträgen und Zahlungsstatus.',
    indicators: {
      columnKeywords: [
        'customer',
        'kunde',
        'kundenkonto',
        'period',
        'abrechnungszeitraum',
        'betrag',
        'amount',
        'payment',
        'rechnung',
        'status',
        'zahlstatus',
        'eur',
      ],
      filenameTokens: ['billing', 'abrechnung', 'invoice', 'faktura'],
      requiredCapabilities: ['billing_summary'],
      criticalFields: ['customerId', 'period', 'amountEUR', 'paymentStatus'],
    },
    fieldProfiles: {
      customerId: {
        aliases: ['customer', 'kunde', 'kundennummer', 'debitor', 'kundenkonto'],
        expectedKinds: ['idlike', 'string'],
      },
      period: {
        aliases: ['period', 'abrechnungszeitraum', 'monat', 'rechnungslauf'],
        expectedKinds: ['date-range', 'string', 'timestamp'],
      },
      amountEUR: {
        aliases: ['betrag', 'amount', 'eur', 'rechnung', 'betrageur'],
        expectedKinds: ['float', 'integer'],
      },
      paymentStatus: {
        aliases: ['payment', 'zahlstatus', 'status', 'bezahlt'],
        expectedKinds: ['string'],
      },
    },
    fixtureFile: 'tests/fixtures/billing_overview.csv',
    exampleQueries: [
      'Wie hoch ist der offene Rechnungsbetrag?',
      'Welche Perioden haben die meisten überfälligen Zahlungen?',
    ],
  },
  {
    id: 'receivables',
    label: 'Receivables',
    department: 'Abrechnung',
    description: 'Offene Posten und Mahnstufen mit Fälligkeit und Beträgen.',
    indicators: {
      columnKeywords: [
        'customer',
        'kunde',
        'due',
        'faellig',
        'faelligkeit',
        'amount',
        'eur',
        'mah',
        'mahnstufe',
        'dunning',
        'open',
        'receivable',
      ],
      filenameTokens: ['receivable', 'forderungen', 'mahnung', 'opos'],
      requiredCapabilities: ['billing_summary'],
      criticalFields: ['customerId', 'dueDate', 'amountEUR', 'dunningLevel'],
    },
    fieldProfiles: {
      customerId: {
        aliases: ['customer', 'kunde', 'kundennummer', 'debitor'],
        expectedKinds: ['idlike', 'string'],
      },
      dueDate: {
        aliases: ['due', 'faellig', 'duedate', 'faelligkeit'],
        expectedKinds: ['timestamp'],
      },
      amountEUR: {
        aliases: ['betrag', 'amount', 'eur', 'offen', 'betrageur'],
        expectedKinds: ['float', 'integer'],
      },
      dunningLevel: {
        aliases: ['dunning', 'mahn', 'mahntufe', 'stufe', 'mahnstufe'],
        expectedKinds: ['integer', 'string'],
      },
    },
    fixtureFile: 'tests/fixtures/receivables.csv',
    exampleQueries: [
      'Wie viele Forderungen sind in Mahnstufe 2 oder höher?',
      'Welche Fälligkeiten konzentrieren das höchste Volumen?',
    ],
  },
  {
    id: 'mako-process-log',
    label: 'MaKo Process Log',
    department: 'Marktkommunikation',
    description: 'Prozesslogs für UTILMD-, GPKE- und WiM-Kommunikation.',
    indicators: {
      columnKeywords: [
        'process',
        'prozess',
        'prozessart',
        'mako',
        'received',
        'eingangszeit',
        'deadline',
        'frist',
        'status',
        'marktkommunikation',
        'utilmd',
        'wim',
      ],
      filenameTokens: ['mako', 'process', 'gpke', 'wim', 'marktkommunikation'],
      requiredCapabilities: ['process_log'],
      criticalFields: ['processType', 'receivedAt', 'deadline', 'status'],
    },
    fieldProfiles: {
      processType: {
        aliases: ['process', 'prozess', 'nachricht', 'utilmd', 'prozessart'],
        expectedKinds: ['string'],
      },
      receivedAt: {
        aliases: ['received', 'eingang', 'receivedat', 'eingangszeit'],
        expectedKinds: ['timestamp'],
      },
      deadline: { aliases: ['deadline', 'frist', 'due'], expectedKinds: ['timestamp'] },
      status: { aliases: ['status', 'state', 'result'], expectedKinds: ['string'] },
    },
    fixtureFile: 'tests/fixtures/mako_process_log.csv',
    exampleQueries: [
      'Welche Prozesse drohen die Frist zu reißen?',
      'Wie viele UTILMD-Nachrichten sind noch offen?',
    ],
  },
  {
    id: 'customer-projects',
    label: 'Customer Projects',
    department: 'Energiedienstleistungen',
    description: 'Projektpipeline für PV-, Speicher-, Wärmepumpen- und Ladeinfrastrukturprojekte.',
    indicators: {
      columnKeywords: [
        'project',
        'projekt',
        'capacity',
        'kapazitaet',
        'kw',
        'status',
        'customer',
        'kunde',
        'typ',
        'pv',
        'wallbox',
      ],
      filenameTokens: ['projects', 'projekte', 'pipeline', 'sales'],
      requiredCapabilities: ['project_pipeline'],
      criticalFields: ['projectId', 'projectType', 'capacityKW', 'status'],
    },
    fieldProfiles: {
      projectId: {
        aliases: ['project', 'projekt', 'projektid', 'chance'],
        expectedKinds: ['idlike', 'string'],
      },
      projectType: {
        aliases: ['type', 'typ', 'projektart', 'solution'],
        expectedKinds: ['string'],
      },
      capacityKW: {
        aliases: ['capacity', 'leistung', 'kw', 'kwp', 'kapazitaetkw'],
        expectedKinds: ['float', 'integer'],
      },
      status: { aliases: ['status', 'phase', 'stage'], expectedKinds: ['string'] },
    },
    fixtureFile: 'tests/fixtures/customer_projects.csv',
    exampleQueries: [
      'Welche Projektarten sind am weitesten fortgeschritten?',
      'Wie viel kW Pipeline sind aktuell in Angebot?',
    ],
  },
  {
    id: 'metering-point-master',
    label: 'Metering Point Master',
    department: 'Energiedatenmanagement',
    description: 'MaLo-/MeLo-Stammdaten mit Tarif- und Netzebeneninformation.',
    indicators: {
      columnKeywords: [
        'malo',
        'melo',
        'zaehlpunkt',
        'zaehler',
        'imsys',
        'rollout',
        'einbau',
        'jahresverbrauch',
        'plz',
        'messlokation',
        'marktlokation',
        'grid',
        'tariff',
        'tarif',
        'netz',
        'ebene',
      ],
      filenameTokens: ['metering-point', 'malo', 'melo', 'stammdaten', 'imsys', 'rollout'],
      requiredCapabilities: ['master_data'],
      criticalFields: ['maloId', 'meloId', 'gridLevel', 'tariffType'],
    },
    fieldProfiles: {
      maloId: { aliases: ['malo', 'marktlokation', 'maloid'], expectedKinds: ['idlike', 'string'] },
      meloId: { aliases: ['melo', 'messlokation', 'meloid'], expectedKinds: ['idlike', 'string'] },
      gridLevel: {
        aliases: ['grid', 'netz', 'ebene', 'spannungsebene'],
        expectedKinds: ['string'],
      },
      tariffType: { aliases: ['tariff', 'tarif', 'tariftyp'], expectedKinds: ['string'] },
    },
    fixtureFile: 'tests/fixtures/metering_point_master.csv',
    exampleQueries: [
      'Welche Tariftypen dominieren je Netzebene?',
      'Wie viele MaLo/MeLo-Paare sind vollständig?',
    ],
  },
];

const semanticDomainMap = new Map(semanticDomains.map((domain) => [domain.id, domain]));

function getSemanticDomainById(domainId) {
  return semanticDomainMap.get(domainId) || null;
}

function listSemanticDomains() {
  return semanticDomains.map((domain) => ({
    id: domain.id,
    label: domain.label,
    department: domain.department,
    description: domain.description,
    criticalFields: [...(domain.indicators?.criticalFields || [])],
    fixtureFile: domain.fixtureFile,
    exampleQueries: [...(domain.exampleQueries || [])],
  }));
}

module.exports = {
  semanticDomains,
  getSemanticDomainById,
  listSemanticDomains,
};
